---
title: "Correlation and basic regression"
date: "2018-10-11"
citeproc: false
bibliography: ../../static/bib/references.bib
csl: ../../static/bib/chicago-syllabus-no-bib.csl
output:
  blogdown::html_page:
    template: ../../pandoc/toc-title_html.template
    toc: true
editor_options: 
  chunk_output_type: console
---

<!-- BLOGDOWN-HEAD -->
<style type="text/css">
a.sourceLine { display: inline-block; line-height: 1.25; }
a.sourceLine { pointer-events: none; color: inherit; text-decoration: inherit; }
a.sourceLine:empty { height: 1.2em; position: absolute; }
.sourceCode { overflow: visible; }
code.sourceCode { white-space: pre; position: relative; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
code.sourceCode { white-space: pre-wrap; }
a.sourceLine { text-indent: -1em; padding-left: 1em; }
}
pre.numberSource a.sourceLine
  { position: relative; }
pre.numberSource a.sourceLine:empty
  { position: absolute; }
pre.numberSource a.sourceLine::before
  { content: attr(data-line-number);
    position: absolute; left: -5em; text-align: right; vertical-align: baseline;
    border: none; pointer-events: all;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    background-color: #ffffff;
    color: #a0a0a0;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #a0a0a0;  padding-left: 4px; }
div.sourceCode
  { color: #1f1c1b; background-color: #ffffff; }
@media screen {
a.sourceLine::before { text-decoration: underline; }
}
code span. { color: #1f1c1b; } /* Normal */
code span.al { color: #bf0303; background-color: #f7e6e6; font-weight: bold; } /* Alert */
code span.an { color: #ca60ca; } /* Annotation */
code span.at { color: #0057ae; } /* Attribute */
code span.bn { color: #b08000; } /* BaseN */
code span.bu { color: #644a9b; font-weight: bold; } /* BuiltIn */
code span.cf { color: #1f1c1b; font-weight: bold; } /* ControlFlow */
code span.ch { color: #924c9d; } /* Char */
code span.cn { color: #aa5500; } /* Constant */
code span.co { color: #898887; } /* Comment */
code span.cv { color: #0095ff; } /* CommentVar */
code span.do { color: #607880; } /* Documentation */
code span.dt { color: #0057ae; } /* DataType */
code span.dv { color: #b08000; } /* DecVal */
code span.er { color: #bf0303; text-decoration: underline; } /* Error */
code span.ex { color: #0095ff; font-weight: bold; } /* Extension */
code span.fl { color: #b08000; } /* Float */
code span.fu { color: #644a9b; } /* Function */
code span.im { color: #ff5500; } /* Import */
code span.in { color: #b08000; } /* Information */
code span.kw { color: #1f1c1b; font-weight: bold; } /* Keyword */
code span.op { color: #1f1c1b; } /* Operator */
code span.ot { color: #006e28; } /* Other */
code span.pp { color: #006e28; } /* Preprocessor */
code span.re { color: #0057ae; background-color: #e0e9f8; } /* RegionMarker */
code span.sc { color: #3daee9; } /* SpecialChar */
code span.ss { color: #ff5500; } /* SpecialString */
code span.st { color: #bf0303; } /* String */
code span.va { color: #0057ae; } /* Variable */
code span.vs { color: #bf0303; } /* VerbatimString */
code span.wa { color: #bf0303; } /* Warning */
</style>
<!-- /BLOGDOWN-HEAD -->

<h2>Contents</h2>
<div id="TOC">
<ul>
<li><a href="#slides">Slides</a></li>
<li><a href="#world-happiness">World happiness</a><ul>
<li><a href="#explore-the-data-and-plot-x-and-y">1. Explore the data and plot X and Y</a></li>
<li><a href="#draw-a-line-that-approximates-the-relationship-between-x-and-y">2. Draw a line that approximates the relationship between X and Y</a></li>
<li><a href="#find-the-mathy-parts-of-the-line">3. Find the mathy parts of the line</a></li>
<li><a href="#interpret-the-math">4. Interpret the math</a></li>
<li><a href="#final-wording-for-a-report">Final wording for a report</a></li>
</ul></li>
<li><a href="#clearest-and-muddiest-things">Clearest and muddiest things</a></li>
</ul>
</div>

<h2 id="slides">Slides</h2>
<p>Download the slides from today’s lecture:</p>
<ul>
<li><a href="/slides/MPA-630_2018-10-11.pdf"><i class="fas fa-file-pdf"></i> PDF (best option)</a></li>
<li><a href="/slides/MPA-630_2018-10-11.pptx"><i class="fas fa-file-powerpoint"></i> PowerPoint</a></li>
</ul>
<figure>
<a href="/slides/MPA-630_2018-10-11.pdf"><img src="/images/slides/slides_2018-10-11.png" alt="First slide" /></a>
</figure>
<h2 id="world-happiness">World happiness</h2>
<p>Here we explore the relationship between national happiness and life expectancy. We follow the same pattern outlined in <em>ModernDive</em> and in class:</p>
<ol style="list-style-type: decimal">
<li>Explore the data and plot X and Y</li>
<li>Draw a line that approximates the relationship between X and Y</li>
<li>Find the mathy parts of the line</li>
<li>Interpret the math</li>
</ol>
<p>I collected this data from the UN and the World Bank. If you’re interested, <a href="/files/create_happiness_data.R">you can see the R script I used to create this dataset here.</a></p>
<p>You can follow along if you download this CSV file:</p>
<ul>
<li><a href="/data/world_happiness.csv"><i class="fas fa-table"></i> <code>world_happiness.csv</code></a></li>
</ul>
<h3 id="explore-the-data-and-plot-x-and-y">1. Explore the data and plot X and Y</h3>
<p>First we load the packages we’ll be using and load the data. Here I assume that the <code>world_happiness.csv</code> file is in a folder named data, but it could be anywhere—adjust the path in <code>read_csv()</code> accordingly.</p>
<div class="sourceCode" id="cb1"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb1-1" data-line-number="1"><span class="co"># Load data and packages</span></a>
<a class="sourceLine" id="cb1-2" data-line-number="2"><span class="kw">library</span>(tidyverse)</a>
<a class="sourceLine" id="cb1-3" data-line-number="3"><span class="kw">library</span>(moderndive)</a>
<a class="sourceLine" id="cb1-4" data-line-number="4"><span class="kw">library</span>(skimr)</a></code></pre></div>
<div class="sourceCode" id="cb2"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb2-1" data-line-number="1">world_happiness &lt;-<span class="st"> </span><span class="kw">read_csv</span>(<span class="st">&quot;data/world_happiness.csv&quot;</span>)</a></code></pre></div>
<p>This data includes a lot of variables. We can see a quick summary of all of them with the <code>glimpse()</code> function, introduced in your ModernDive reading. There are 11 variables and 217 rows:</p>
<div class="sourceCode" id="cb3"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb3-1" data-line-number="1"><span class="kw">glimpse</span>(world_happiness)</a></code></pre></div>
<pre><code>## Observations: 217
## Variables: 11
## $ iso2c                 &lt;chr&gt; &quot;AD&quot;, &quot;AE&quot;, &quot;AF&quot;, &quot;AG&quot;, &quot;AL&quot;, &quot;AM&quot;, &quot;AO&quot;...
## $ happiness_score       &lt;dbl&gt; NA, 6.901, 3.575, NA, 4.959, 4.350, 4.03...
## $ happiness_se          &lt;dbl&gt; NA, 0.03729, 0.03084, NA, 0.05013, 0.047...
## $ country               &lt;chr&gt; &quot;Andorra&quot;, &quot;United Arab Emirates&quot;, &quot;Afgh...
## $ year                  &lt;int&gt; 2015, 2015, 2015, 2015, 2015, 2015, 2015...
## $ school_enrollment     &lt;dbl&gt; NA, 93.38943, NA, 78.57764, 95.19960, 92...
## $ life_expectancy       &lt;dbl&gt; NA, 77.10100, 63.28800, 76.20700, 78.174...
## $ access_to_electricity &lt;dbl&gt; 100.00000, 100.00000, 71.50000, 96.82629...
## $ gdp_per_cap           &lt;dbl&gt; 41765.9204, 40753.8863, 620.0565, 12771....
## $ region                &lt;chr&gt; &quot;Europe &amp; Central Asia&quot;, &quot;Middle East &amp; ...
## $ income                &lt;chr&gt; &quot;High income&quot;, &quot;High income&quot;, &quot;Low incom...</code></pre>
<p>For this example, we care most about <code>happiness_score</code> and <code>life_expectancy</code>. We can find summary statistics for both using the <code>skim()</code> function (also introduced in ModernDive):</p>
<div class="sourceCode" id="cb5"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb5-1" data-line-number="1">world_happiness <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb5-2" data-line-number="2"><span class="st">  </span><span class="kw">select</span>(happiness_score, life_expectancy) <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb5-3" data-line-number="3"><span class="st">  </span><span class="kw">skim</span>()</a></code></pre></div>
<pre><code>## Skim summary statistics
##  n obs: 217 
##  n variables: 2 
## 
## Variable type: numeric 
##         variable missing complete   n  mean   sd    p0   p25   p50   p75
##  happiness_score      62      155 217  5.37 1.15  2.84  4.52  5.21  6.22
##  life_expectancy      19      198 217 72.07 7.88 51.41 66.5  74.19 77.42
##   p100     hist
##   7.59 ▁▃▆▇▅▆▅▃
##  84.28 ▁▂▃▃▅▇▆▆</code></pre>
<p>We can learn a lot just from this table. The smallest value of happiness (<code>p0</code>) is 2.84, while the highest (<code>p100</code>) is 7.59, while the average is 5.37. Life expectancy ranges from 51.41 to 84.28, with an average of 72.07. The histogram column shows the distribution of each variable.</p>
<p>We can also find the correlation between these two variables, which shows how closely the two are related, and in which direction. <em>HOWEVER</em>, using the fancy <code>get_correlation()</code> function won’t work because there are missing values, and as we learned with calculating means and sums, R doesn’t know what to do when it encounters missing values, so it just returns <code>NA</code></p>
<div class="sourceCode" id="cb7"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb7-1" data-line-number="1"><span class="co"># so sad</span></a>
<a class="sourceLine" id="cb7-2" data-line-number="2">world_happiness <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb7-3" data-line-number="3"><span class="st">  </span><span class="kw">get_correlation</span>(happiness_score <span class="op">~</span><span class="st"> </span>life_expectancy)</a></code></pre></div>
<pre><code>## # A tibble: 1 x 1
##   correlation
##         &lt;dbl&gt;
## 1          NA</code></pre>
<p>There are two ways to fix this. First, we can filter out all the rows where happiness or life expectancy is missing, and then use <code>get_correlation()</code>. The <code>is.na()</code> function determines if something is missing. Negating it with <code>!</code> like <code>!is.na()</code> means “check if the value is not missing”.</p>
<div class="sourceCode" id="cb9"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb9-1" data-line-number="1">world_happiness <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb9-2" data-line-number="2"><span class="st">  </span><span class="kw">filter</span>(<span class="op">!</span><span class="kw">is.na</span>(happiness_score), <span class="op">!</span><span class="kw">is.na</span>(life_expectancy)) <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb9-3" data-line-number="3"><span class="st">  </span><span class="kw">get_correlation</span>(happiness_score <span class="op">~</span><span class="st"> </span>life_expectancy)</a></code></pre></div>
<pre><code>## # A tibble: 1 x 1
##   correlation
##         &lt;dbl&gt;
## 1       0.743</code></pre>
<p>Alternatively, you can not use the <code>get_correlation()</code> function and instead use <code>cor()</code>, which is R’s actual function for finding correlation. If you look at the help file for <code>cor()</code>, you’ll see that there’s an argument that tells R what to do with missing data, similar to the <code>na.rm = TRUE</code> concept that we saw with <code>mean()</code> and <code>sum()</code>. By default, <code>cor()</code> will use all rows from both of the variables you’re correlating, which means it chokes when there is missing data. Instead of using everything, you can use only the rows with complete observations (i.e. where there’s data for both happiness and life expectancy). Here’s how you use the <code>use</code> argument to tell R to only look at complete rows:</p>
<div class="sourceCode" id="cb11"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb11-1" data-line-number="1">world_happiness <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb11-2" data-line-number="2"><span class="st">  </span><span class="kw">summarize</span>(<span class="dt">happy_life_correlation =</span> <span class="kw">cor</span>(happiness_score, life_expectancy, </a>
<a class="sourceLine" id="cb11-3" data-line-number="3">                                         <span class="dt">use =</span> <span class="st">&quot;complete.obs&quot;</span>))</a></code></pre></div>
<pre><code>## # A tibble: 1 x 1
##   happy_life_correlation
##                    &lt;dbl&gt;
## 1                  0.743</code></pre>
<p>Phew. Back to interpretation now. The correlation coefficient for national happiness and life expectacny is 0.743. With that, you can write the following sentences, using the template we talked about in class:</p>
<blockquote>
<p>National happiness and life expectancy are positively and strongly correlated. As life expectancy increases, happiness also tends to improve (r = 0.743).</p>
</blockquote>
<p>Finally, let’s make a scatterplot of the two variables (it will warn you that it couldn’t plot some of the points—that’s fine. We knew from looking at the <code>skim</code> table above that some of these countries have missing data):</p>
<div class="sourceCode" id="cb13"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb13-1" data-line-number="1"><span class="kw">ggplot</span>(world_happiness, <span class="kw">aes</span>(<span class="dt">x =</span> life_expectancy, <span class="dt">y =</span> happiness_score)) <span class="op">+</span></a>
<a class="sourceLine" id="cb13-2" data-line-number="2"><span class="st">  </span><span class="kw">geom_point</span>()</a></code></pre></div>
<pre><code>## Warning: Removed 62 rows containing missing values (geom_point).</code></pre>
<p><img src="/class/06-class_files/figure-html/plot-correlation-1.png" width="672" /></p>
<p>That looks like a good positive relationship!</p>
<h3 id="draw-a-line-that-approximates-the-relationship-between-x-and-y">2. Draw a line that approximates the relationship between X and Y</h3>
<p>Next, we want to draw a straight line that captures the relationship between the two. As we discussed in class (and as you read in ModernDive), the line should minimize the (squared) distance between each point and the line. R does this for you—you’ll never have to do this by hand. Use <code>geom_smooth(method = &quot;lm&quot;)</code> to add a straight line.</p>
<div class="sourceCode" id="cb15"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb15-1" data-line-number="1"><span class="kw">ggplot</span>(world_happiness, <span class="kw">aes</span>(<span class="dt">x =</span> life_expectancy, <span class="dt">y =</span> happiness_score)) <span class="op">+</span></a>
<a class="sourceLine" id="cb15-2" data-line-number="2"><span class="st">  </span><span class="kw">geom_point</span>() <span class="op">+</span></a>
<a class="sourceLine" id="cb15-3" data-line-number="3"><span class="st">  </span><span class="kw">geom_smooth</span>(<span class="dt">method =</span> <span class="st">&quot;lm&quot;</span>)</a></code></pre></div>
<pre><code>## Warning: Removed 62 rows containing non-finite values (stat_smooth).</code></pre>
<pre><code>## Warning: Removed 62 rows containing missing values (geom_point).</code></pre>
<p><img src="/class/06-class_files/figure-html/plot-correlation-smooth-1.png" width="672" /></p>
<h3 id="find-the-mathy-parts-of-the-line">3. Find the mathy parts of the line</h3>
<p>Next, we need to find the slope and y-intercept of this line. Remember that we can define any line mathematically with the equation</p>
<p><span class="math display">\[
y = mx + b
\]</span></p>
<p>or</p>
<p><span class="math display">\[
y = b + mx
\]</span></p>
<p>where <span class="math inline">\(m\)</span> is the slope (<span class="math inline">\(\frac{\text{rise}}{\text{run}}\)</span>), and <span class="math inline">\(b\)</span> is the point where the line crosses the y-axis.</p>
<p>In stats terminology, we write this equation with betas instead of <span class="math inline">\(m\)</span> and <span class="math inline">\(b\)</span>:</p>
<p><span class="math display">\[
\hat{y} = \beta_0 + \beta_1x_1 + \epsilon
\]</span></p>
<p>where <span class="math inline">\(\beta_0\)</span> is the y-intercept and <span class="math inline">\(\beta_1\)</span> is the slope.</p>
<p>We can calculate these coefficients with the <code>lm()</code> function (or linear model). We feed the function two things: a formula and a data frame. The formula follows the pattern <code>y ~ x</code> (or in English, “y is explained by x”). In this situation, happiness is our outcome variable and life expectancy is our explanatory variable, so the formula would be <code>happiness_score ~ life_expectancy</code> (or “happiness is explained by life expectancy”). Here I name the model <code>model1</code>, but that’s just a name I made up. You can call it anything (<code>happy_life_model</code> maybe):</p>
<div class="sourceCode" id="cb18"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb18-1" data-line-number="1">model1 &lt;-<span class="st"> </span><span class="kw">lm</span>(happiness_score <span class="op">~</span><span class="st"> </span>life_expectancy, <span class="dt">data =</span> world_happiness)</a></code></pre></div>
<p>We can see the full model details with the <code>get_regression_table()</code> function:</p>
<div class="sourceCode" id="cb19"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb19-1" data-line-number="1">model1 <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb19-2" data-line-number="2"><span class="st">  </span><span class="kw">get_regression_table</span>()</a></code></pre></div>
<pre><code>## # A tibble: 2 x 7
##   term            estimate std_error statistic p_value lower_ci upper_ci
##   &lt;chr&gt;              &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;   &lt;dbl&gt;    &lt;dbl&gt;    &lt;dbl&gt;
## 1 intercept         -2.22      0.556     -3.98       0    -3.31   -1.12 
## 2 life_expectancy    0.105     0.008     13.7        0     0.09    0.121</code></pre>
<p>We now have an intercept or <span class="math inline">\(\beta_0\)</span> (-2.22) and a slope or <span class="math inline">\(\beta_1\)</span> (0.105), which means we can write the full equation for this line:</p>
<p><span class="math display">\[
\hat{\text{happiness}} = -2.22 + 0.105 \times \text{life expectancy} + \epsilon
\]</span></p>
<h3 id="interpret-the-math">4. Interpret the math</h3>
<p>Finally, we can interpet what these betas (or coefficients) actually mean. Remember that for now, all we care about are the <code>term</code> and <code>estimate</code> columns—we’ll cover what the other columns are later:</p>
<div class="sourceCode" id="cb21"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb21-1" data-line-number="1">model1 <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb21-2" data-line-number="2"><span class="st">  </span><span class="kw">get_regression_table</span>()</a></code></pre></div>
<pre><code>## # A tibble: 2 x 7
##   term            estimate std_error statistic p_value lower_ci upper_ci
##   &lt;chr&gt;              &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;   &lt;dbl&gt;    &lt;dbl&gt;    &lt;dbl&gt;
## 1 intercept         -2.22      0.556     -3.98       0    -3.31   -1.12 
## 2 life_expectancy    0.105     0.008     13.7        0     0.09    0.121</code></pre>
<p>The intercept of -2.22 means that this line crosses the y-axis at -2.22. It doesn’t look like this in the graph, though. There it looks like it crosses at 3ish. That’s because the graph is zoomed in and the x-axis starts at 50. If we zoom out and include 0 in the x-axis, we can see that the actual y-intercept is really just below -2.</p>
<div class="sourceCode" id="cb23"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb23-1" data-line-number="1"><span class="kw">ggplot</span>(world_happiness, <span class="kw">aes</span>(<span class="dt">x =</span> life_expectancy, <span class="dt">y =</span> happiness_score)) <span class="op">+</span></a>
<a class="sourceLine" id="cb23-2" data-line-number="2"><span class="st">  </span><span class="kw">geom_point</span>() <span class="op">+</span></a>
<a class="sourceLine" id="cb23-3" data-line-number="3"><span class="st">  </span><span class="co"># fullrange = TRUE means that the line will go beyond the points</span></a>
<a class="sourceLine" id="cb23-4" data-line-number="4"><span class="st">  </span><span class="kw">geom_smooth</span>(<span class="dt">method =</span> <span class="st">&quot;lm&quot;</span>, <span class="dt">fullrange =</span> <span class="ot">TRUE</span>) <span class="op">+</span></a>
<a class="sourceLine" id="cb23-5" data-line-number="5"><span class="st">  </span><span class="co"># This forces the x axis to include 0</span></a>
<a class="sourceLine" id="cb23-6" data-line-number="6"><span class="st">  </span><span class="kw">expand_limits</span>(<span class="dt">x =</span> <span class="dv">0</span>)</a></code></pre></div>
<pre><code>## Warning: Removed 62 rows containing non-finite values (stat_smooth).</code></pre>
<pre><code>## Warning: Removed 62 rows containing missing values (geom_point).</code></pre>
<p><img src="/class/06-class_files/figure-html/plot-model-zoom-out-1.png" width="672" /></p>
<p>In this case, because there aren’t any countries with life expectancies of zero, the actual value of the intercept isn’t that important. Technically it means that a country with a life expectancy of zero would have an average associated happiness level of -2.22. But that’s non-sensical.</p>
<p>What is important, though, is the value of the <span class="math inline">\(\beta_1\)</span> coefficient, or the slope of life expectancy. This tells us that for every unit increase in life expectancy, there’s an associated increase in happiness of 0.105. If life expectancy increase by 10 years, we could predict an associated increase in happiness of 1.05 points, on average. Neat!</p>
<p>We can use the following template to interpret this coefficient:</p>
<blockquote>
<p>A one unit increase in life expectancy is associated with a 0.105 point increase in happiness, on average.</p>
</blockquote>
<p>Don’t succumb to the temptation to tell a causal story, though. Life expectancy doesn’t necessarily cause happiness. The reverse story is just as plausible (as life expectancy increases, happiness will increases). There’s no mathematical or statistical way to test for causation though—it’s all a question of theory and philosophy.</p>
<p>And that’s it! We’ve run a regression model and interpreted the results.</p>
<p>Here’s what this would all look like in an actual policy report or academic paper:</p>
<h3 id="final-wording-for-a-report">Final wording for a report</h3>
<p>Does living longer make you happier? Using data from the World Bank and UN, we examined the relationship between life expectancy and national happiness. As seen in Figure 1 below, the two measures are strongly and positively correlated—as life expectancy increases, happiness also tends to improve (r = 0.743). Table 1 provides the results from an OLS regression model, with happiness as the outcome variable. The model shows that a one year increase in life expectancy is associated with a 0.105 point increase in national happiness, on average.</p>
<p>This is most assuredly <em>not</em> decisive evidence that longer life leads to greater happiness, though. The mechanisms that cause better life expectancy (better access to healthcare, political stability, absence of violence, better access to food, etc.) also all probably improve national happiness. Moreover, there is a plausible story of reverse causality—greater happiness might make you live longer. Regardless, we can see that there is a positive relationship between the two and that on average, countries that make improvements to life expectancy can expect greater national happiness.</p>
<div class="sourceCode" id="cb26"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb26-1" data-line-number="1"><span class="co"># Tweak the graph a little to make it more publication-worthy</span></a>
<a class="sourceLine" id="cb26-2" data-line-number="2"><span class="co">#</span></a>
<a class="sourceLine" id="cb26-3" data-line-number="3"><span class="co"># In a real, real-life report you wouldn&#39;t want to include this code. You can</span></a>
<a class="sourceLine" id="cb26-4" data-line-number="4"><span class="co"># make it so it doesn&#39;t show in the knitted document by adding `echo=FALSE` to</span></a>
<a class="sourceLine" id="cb26-5" data-line-number="5"><span class="co"># the chunk options.</span></a>
<a class="sourceLine" id="cb26-6" data-line-number="6"><span class="kw">ggplot</span>(world_happiness, <span class="kw">aes</span>(<span class="dt">x =</span> life_expectancy, <span class="dt">y =</span> happiness_score)) <span class="op">+</span></a>
<a class="sourceLine" id="cb26-7" data-line-number="7"><span class="st">  </span><span class="kw">geom_point</span>() <span class="op">+</span></a>
<a class="sourceLine" id="cb26-8" data-line-number="8"><span class="st">  </span><span class="kw">geom_smooth</span>(<span class="dt">method =</span> <span class="st">&quot;lm&quot;</span>) <span class="op">+</span></a>
<a class="sourceLine" id="cb26-9" data-line-number="9"><span class="st">  </span><span class="kw">labs</span>(<span class="dt">x =</span> <span class="st">&quot;Life expectancy&quot;</span>, <span class="dt">y =</span> <span class="st">&quot;National happiness&quot;</span>,</a>
<a class="sourceLine" id="cb26-10" data-line-number="10">       <span class="dt">title =</span> <span class="st">&quot;Figure 1: Relationship between life expectancy and national happiness&quot;</span>,</a>
<a class="sourceLine" id="cb26-11" data-line-number="11">       <span class="dt">caption =</span> <span class="st">&quot;Source: UN World Happiness Report and World Bank Development Indicators&quot;</span>) <span class="op">+</span></a>
<a class="sourceLine" id="cb26-12" data-line-number="12"><span class="st">  </span><span class="kw">theme_minimal</span>()</a></code></pre></div>
<p><img src="/class/06-class_files/figure-html/nice-figure-1-1.png" width="672" /></p>
<table>
<caption>Table 1: OLS regression results</caption>
<colgroup>
<col width="21%" />
<col width="12%" />
<col width="14%" />
<col width="14%" />
<col width="11%" />
<col width="12%" />
<col width="12%" />
</colgroup>
<thead>
<tr class="header">
<th align="left">term</th>
<th align="center">estimate</th>
<th align="center">std_error</th>
<th align="center">statistic</th>
<th align="center">p_value</th>
<th align="center">lower_ci</th>
<th align="center">upper_ci</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">intercept</td>
<td align="center">-2.215</td>
<td align="center">0.556</td>
<td align="center">-3.983</td>
<td align="center">0</td>
<td align="center">-3.313</td>
<td align="center">-1.116</td>
</tr>
<tr class="even">
<td align="left">life_expectancy</td>
<td align="center">0.105</td>
<td align="center">0.008</td>
<td align="center">13.73</td>
<td align="center">0</td>
<td align="center">0.09</td>
<td align="center">0.121</td>
</tr>
</tbody>
</table>
<h2 id="clearest-and-muddiest-things">Clearest and muddiest things</h2>
<p>Go to <a href="https://goo.gl/forms/PlPwZGhMOdU9mKfC3">this form</a> and answer these three questions:</p>
<ol style="list-style-type: decimal">
<li>What was the muddiest thing from class today? What are you still wondering about?</li>
<li>What was the clearest thing from class today?</li>
<li>What was the most exciting thing you learned?</li>
</ol>
<p>I’ll compile the questions and send out answers after class.</p>
