---
title: "Regression diagnostics and prediction"
date: "2018-10-25"
citeproc: false
bibliography: ../../static/bib/references.bib
csl: ../../static/bib/chicago-syllabus-no-bib.csl
output:
  blogdown::html_page:
    template: ../../pandoc/toc-title_html.template
    toc: true
    toc_depth: 4
editor_options: 
  chunk_output_type: console
---

<!-- BLOGDOWN-HEAD -->
<style type="text/css">
a.sourceLine { display: inline-block; line-height: 1.25; }
a.sourceLine { pointer-events: none; color: inherit; text-decoration: inherit; }
a.sourceLine:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode { white-space: pre; position: relative; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
code.sourceCode { white-space: pre-wrap; }
a.sourceLine { text-indent: -1em; padding-left: 1em; }
}
pre.numberSource a.sourceLine
  { position: relative; left: -4em; }
pre.numberSource a.sourceLine::before
  { content: attr(title);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; pointer-events: all; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    background-color: #ffffff;
    color: #a0a0a0;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #a0a0a0;  padding-left: 4px; }
div.sourceCode
  { color: #1f1c1b; background-color: #ffffff; }
@media screen {
a.sourceLine::before { text-decoration: underline; }
}
code span. { color: #1f1c1b; } /* Normal */
code span.al { color: #bf0303; background-color: #f7e6e6; font-weight: bold; } /* Alert */
code span.an { color: #ca60ca; } /* Annotation */
code span.at { color: #0057ae; } /* Attribute */
code span.bn { color: #b08000; } /* BaseN */
code span.bu { color: #644a9b; font-weight: bold; } /* BuiltIn */
code span.cf { color: #1f1c1b; font-weight: bold; } /* ControlFlow */
code span.ch { color: #924c9d; } /* Char */
code span.cn { color: #aa5500; } /* Constant */
code span.co { color: #898887; } /* Comment */
code span.cv { color: #0095ff; } /* CommentVar */
code span.do { color: #607880; } /* Documentation */
code span.dt { color: #0057ae; } /* DataType */
code span.dv { color: #b08000; } /* DecVal */
code span.er { color: #bf0303; text-decoration: underline; } /* Error */
code span.ex { color: #0095ff; font-weight: bold; } /* Extension */
code span.fl { color: #b08000; } /* Float */
code span.fu { color: #644a9b; } /* Function */
code span.im { color: #ff5500; } /* Import */
code span.in { color: #b08000; } /* Information */
code span.kw { color: #1f1c1b; font-weight: bold; } /* Keyword */
code span.op { color: #1f1c1b; } /* Operator */
code span.ot { color: #006e28; } /* Other */
code span.pp { color: #006e28; } /* Preprocessor */
code span.re { color: #0057ae; background-color: #e0e9f8; } /* RegionMarker */
code span.sc { color: #3daee9; } /* SpecialChar */
code span.ss { color: #ff5500; } /* SpecialString */
code span.st { color: #bf0303; } /* String */
code span.va { color: #0057ae; } /* Variable */
code span.vs { color: #bf0303; } /* VerbatimString */
code span.wa { color: #bf0303; } /* Warning */
</style>
<!-- /BLOGDOWN-HEAD -->

<h2>Contents</h2>
<div id="TOC">
<ul>
<li><a href="#slides">Slides</a></li>
<li><a href="#code-from-today">Code from today</a><ul>
<li><a href="#load-and-wrangle-data">Load and wrangle data</a></li>
<li><a href="#us-presidential-election">2016 US Presidential Election</a><ul>
<li><a href="#percent-democratic-explained-by-age">Percent democratic explained by age</a></li>
<li><a href="#percent-democratic-explained-by-age-and-race">Percent democratic explained by age and race</a></li>
<li><a href="#percent-democratic-explained-by-lots-of-things">Percent democratic explained by lots of things</a></li>
<li><a href="#all-models-side-by-side">All models side-by-side</a></li>
</ul></li>
<li><a href="#brexit">Brexit</a><ul>
<li><a href="#leave-share-explained-by-immigration">Leave share explained by immigration</a></li>
<li><a href="#leave-share-explained-by-education-and-age">Leave share explained by education and age</a></li>
<li><a href="#leave-share-explained-by-political-party">Leave share explained by political party</a></li>
<li><a href="#leave-share-explained-by-lots-of-things">Leave share explained by lots of things</a></li>
<li><a href="#making-predictions">Making predictions</a></li>
<li><a href="#all-models-side-by-side-1">All models side-by-side</a></li>
</ul></li>
</ul></li>
<li><a href="#clearest-and-muddiest-things">Clearest and muddiest things</a></li>
</ul>
</div>

<h2 id="slides">Slides</h2>
<p>Download the slides from today’s lecture:</p>
<ul>
<li><a href="/slides/MPA-630_2018-10-25.pdf"><i class="fas fa-file-pdf"></i> PDF (best option)</a></li>
<li><a href="/slides/MPA-630_2018-10-25.pptx"><i class="fas fa-file-powerpoint"></i> PowerPoint</a></li>
</ul>
<figure>
<a href="/slides/MPA-630_2018-10-25.pdf"><img src="/images/slides/slides_2018-10-25.png" alt="First slide" /></a>
</figure>
<h2 id="code-from-today">Code from today</h2>
<p>In class we used multiple regression to explore the factors that explain the 2016 US presidential election results and the results of the 2016 Brexit vote in the UK.</p>
<p>You can download these files from here if you want to follow along (make an RStudio project, put them in a data folder, and you’ll be good to go):</p>
<ul>
<li><a href="/data/results_2016.csv"><i class="fas fa-table"></i> <code>results_2016.csv</code></a><span><label for="sn-1" class="margin-toggle sidenote-number"></label><input type="checkbox" id="sn-1" class="margin-toggle"/><span class="sidenote">This data comes from the <a href="https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/VOQCHQ">MIT Election Data and Science Lab</a><br />
<br />
</span></span></li>
<li><a href="/data/brexit_results.csv"><i class="fas fa-table"></i> <code>brexit_results.csv</code></a><span><label for="sn-2" class="margin-toggle sidenote-number"></label><input type="checkbox" id="sn-2" class="margin-toggle"/><span class="sidenote">This data comes from <a href="https://www.thecrosstab.com/">Elliott Morris</a>, who cleaned it up and made it available through his <del>DataCamp class (which you should check out while you have access to the full DataCamp library!)</del><br />
<br />
</span></span></li>
</ul>
<h3 id="load-and-wrangle-data">Load and wrangle data</h3>
<p>First we load the necessary packages:</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">library</span>(tidyverse)
<span class="kw">library</span>(moderndive)

<span class="co"># The broom package lets us manipulate model objects and makes it easier to</span>
<span class="co"># generate predictions and plot them</span>
<span class="kw">library</span>(broom)</code></pre>
<p>Then we load the data. The data is already precleaned and tidy and ready to use, so we don’t have to do any wrangling here.</p>
<pre class="sourceCode r"><code class="sourceCode r">results_<span class="dv">2016</span> &lt;-<span class="st"> </span><span class="kw">read_csv</span>(<span class="st">&quot;data/results_2016.csv&quot;</span>)
results_brexit &lt;-<span class="st"> </span><span class="kw">read_csv</span>(<span class="st">&quot;data/brexit_results.csv&quot;</span>)</code></pre>
<h3 id="us-presidential-election">2016 US Presidential Election</h3>
<p>Let’s explore variation in democratic party vote share in 2016. Our main outcome variable (or y) is <code>percent_dem</code>, which is the percent of presidential votes cast for the Democratic party (on a scale of 0–100). Here’s a histogram to give you a sense of the data. King County, Texas only had 3% of its presidential votes cast for Hilary Clinton, while 90% of Washington, DC voted for her.</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">ggplot</span>(results_<span class="dv">2016</span>, <span class="kw">aes</span>(<span class="dt">x =</span> percent_dem)) <span class="op">+</span>
<span class="st">  </span><span class="kw">geom_histogram</span>(<span class="dt">binwidth =</span> <span class="fl">2.5</span>)</code></pre>
<p><img src="/class/08-class_files/figure-html/dist-votes-us-1.png" width="672" /></p>
<h4 id="percent-democratic-explained-by-age">Percent democratic explained by age</h4>
<p>Let’s first test the old adage that people become more conservative as they get older. The correlation between a county’s median and age and the democratic vote share is moderately negative:</p>
<pre class="sourceCode r"><code class="sourceCode r">results_<span class="dv">2016</span> <span class="op">%&gt;%</span><span class="st"> </span>
<span class="st">  </span><span class="co"># There are some missing values in each of these columns, so we have to filter</span>
<span class="st">  </span><span class="co"># them out first before checking the correlation</span>
<span class="st">  </span><span class="kw">filter</span>(<span class="op">!</span><span class="kw">is.na</span>(percent_dem), <span class="op">!</span><span class="kw">is.na</span>(median_age)) <span class="op">%&gt;%</span><span class="st"> </span>
<span class="st">  </span><span class="kw">get_correlation</span>(percent_dem <span class="op">~</span><span class="st"> </span>median_age)</code></pre>
<pre><code>## # A tibble: 1 x 1
##   correlation
##         &lt;dbl&gt;
## 1      -0.298</code></pre>
<p>It looks negative too:</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">ggplot</span>(results_<span class="dv">2016</span>, <span class="kw">aes</span>(<span class="dt">x =</span> median_age, <span class="dt">y =</span> percent_dem)) <span class="op">+</span>
<span class="st">  </span><span class="kw">geom_point</span>(<span class="dt">alpha =</span> <span class="fl">0.25</span>) <span class="op">+</span>
<span class="st">  </span><span class="kw">geom_smooth</span>(<span class="dt">method =</span> <span class="st">&quot;lm&quot;</span>)</code></pre>
<p><img src="/class/08-class_files/figure-html/dem-votes-age-plot-1.png" width="672" /></p>
<p>If we run a regression model, we can find the slope and <span class="math inline">\(R^2\)</span> and other information:</p>
<pre class="sourceCode r"><code class="sourceCode r">us_dem_age &lt;-<span class="st"> </span><span class="kw">lm</span>(percent_dem <span class="op">~</span><span class="st"> </span>median_age, <span class="dt">data =</span> results_<span class="dv">2016</span>)

<span class="kw">get_regression_table</span>(us_dem_age)</code></pre>
<pre><code>## # A tibble: 2 x 7
##   term       estimate std_error statistic p_value lower_ci upper_ci
##   &lt;chr&gt;         &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;   &lt;dbl&gt;    &lt;dbl&gt;    &lt;dbl&gt;
## 1 intercept    67.5       2.09       32.4       0   63.4     71.6  
## 2 median_age   -0.887     0.051     -17.4       0   -0.987   -0.787</code></pre>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">get_regression_summaries</span>(us_dem_age)</code></pre>
<pre><code>## # A tibble: 1 x 8
##   r_squared adj_r_squared   mse  rmse sigma statistic p_value    df
##       &lt;dbl&gt;         &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;     &lt;dbl&gt;   &lt;dbl&gt; &lt;dbl&gt;
## 1     0.089         0.088  212.  14.6  14.6      302.       0     2</code></pre>
<p>The intercept here (<span class="math inline">\(\beta_0\)</span>) means that in a hypothetical county where the median age is 0 years, the predicted democratic vote share would be 67.5%. That’s impossible though, because no counties consist entirely of babies. So we can ignore it.</p>
<p>The slope for median age (<span class="math inline">\(\beta_1\)</span>) is -0.887. This means that on average, a 1 year increase in the median age in a county is associated with a drop in democratic vote share of 0.887%. Or in other words, if a county that had 40% voting for democrats got a year older, we could predict a democratic vote share of 39.113% (40 − 0.887).</p>
<p>The <span class="math inline">\(R^2\)</span> is 0.089 (we use the regular <span class="math inline">\(R^2\)</span> because we only have one explanatory variable), which means that this model explains 8.9% of the variation in democratic vote share. It’s not that great of a model.</p>
<h4 id="percent-democratic-explained-by-age-and-race">Percent democratic explained by age and race</h4>
<p>We can improve the model by including additional explanatory variables, such as race:</p>
<pre class="sourceCode r"><code class="sourceCode r">model_age_dem_race &lt;-<span class="st"> </span><span class="kw">lm</span>(percent_dem <span class="op">~</span><span class="st"> </span>median_age <span class="op">+</span><span class="st"> </span>percent_white, 
                         <span class="dt">data =</span> results_<span class="dv">2016</span>)

<span class="kw">get_regression_table</span>(model_age_dem_race)</code></pre>
<pre><code>## # A tibble: 3 x 7
##   term          estimate std_error statistic p_value lower_ci upper_ci
##   &lt;chr&gt;            &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;   &lt;dbl&gt;    &lt;dbl&gt;    &lt;dbl&gt;
## 1 intercept       70.4       1.76      39.9    0       66.9     73.8  
## 2 median_age      -0.094     0.049     -1.93   0.053   -0.189    0.001
## 3 percent_white   -0.448     0.013    -35.3    0       -0.473   -0.423</code></pre>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">get_regression_summaries</span>(model_age_dem_race)</code></pre>
<pre><code>## # A tibble: 1 x 8
##   r_squared adj_r_squared   mse  rmse sigma statistic p_value    df
##       &lt;dbl&gt;         &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;     &lt;dbl&gt;   &lt;dbl&gt; &lt;dbl&gt;
## 1      0.35         0.349  151.  12.3  12.3      836.       0     3</code></pre>
<p>Now we have two coefficients to work through (again, the intercept is nonsensical; it shows what the democratic vote share would be if the median age were 0 and if the percent of white people in a county were 0%).</p>
<p>The slope for median age (<span class="math inline">\(\beta_1\)</span>) is -0.094, which means that controlling for race, a 1 year increase in age is associated with a decrease in democratic vote share of 0.094, on average. This means that in a hypothetical county where 40% voted for democrats, we could predict that bumping age up by a year would result in 39.906%. That’s a tiny effect—controlling for race took away most of the effect of age from the previous model.</p>
<p>The coefficient for percent white (<span class="math inline">\(\beta_2\)</span>) is -0.448, which means that controlling for age, a 1% increase in the proportion of whites in a county is associated with a drop in democratic vote share of 0.448, on average. This would be like moving from 40% to 39.552%.</p>
<p>To explain model fit, we need to look at the adjusted <span class="math inline">\(R^2\)</span> because we’re using more than one explanatory variable. This model explains 34.9% of the variation in democratic vote share. It’s getting better!</p>
<h4 id="percent-democratic-explained-by-lots-of-things">Percent democratic explained by lots of things</h4>
<p>Now let’s throw in a ton of explanatory variables to see what other factors might explain democratic vote share:</p>
<pre class="sourceCode r"><code class="sourceCode r">model_lots_of_stuff &lt;-<span class="st"> </span><span class="kw">lm</span>(percent_dem <span class="op">~</span><span class="st"> </span>median_age <span class="op">+</span><span class="st"> </span>percent_white <span class="op">+</span><span class="st"> </span>
<span class="st">                            </span>per_capita_income <span class="op">+</span><span class="st"> </span>median_rent <span class="op">+</span><span class="st"> </span>state,
                          <span class="dt">data =</span> results_<span class="dv">2016</span>)

<span class="kw">get_regression_table</span>(model_lots_of_stuff)</code></pre>
<pre><code>## # A tibble: 54 x 7
##    term              estimate std_error statistic p_value lower_ci upper_ci
##    &lt;chr&gt;                &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;   &lt;dbl&gt;    &lt;dbl&gt;    &lt;dbl&gt;
##  1 intercept           58.5       1.66      35.3    0       55.2     61.8  
##  2 median_age           0.166     0.037      4.52   0        0.094    0.238
##  3 percent_white       -0.682     0.011    -61.9    0       -0.704   -0.661
##  4 per_capita_income    0         0          5.46   0        0        0    
##  5 median_rent          0.02      0.002     12.3    0        0.017    0.023
##  6 stateArizona        -7.96      2.18      -3.65   0      -12.2     -3.69 
##  7 stateArkansas        4.08      1.28       3.19   0.001    1.57     6.58 
##  8 stateCalifornia     -2.45      1.50      -1.64   0.102   -5.38     0.485
##  9 stateColorado        1.81      1.36       1.34   0.182   -0.848    4.47 
## 10 stateConnecticut    11.8       2.87       4.10   0        6.12    17.4  
## # … with 44 more rows</code></pre>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">get_regression_summaries</span>(model_lots_of_stuff)</code></pre>
<pre><code>## # A tibble: 1 x 8
##   r_squared adj_r_squared   mse  rmse sigma statistic p_value    df
##       &lt;dbl&gt;         &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;     &lt;dbl&gt;   &lt;dbl&gt; &lt;dbl&gt;
## 1     0.759         0.755  56.1  7.49  7.56      182.       0    54</code></pre>
<p>Now we’re controlling for age, race, income, rent, and state, which gives our model a lot more explanatory power. The adjusted <span class="math inline">\(R^2\)</span> is 0.755, which means that this model explains 75.5% of the variation in democratic vote share. Neat!</p>
<p>Interestingly, when controlling for race, income, rent prices, and state, the coefficient for age is now positive—a 1 year increase in the median age in a county is associated with a 0.166 unit increase in the share of democratic votes (e.g. moving from 40% to 40.166%), on average. This goes contrary to the old adage that people vote more conservative as they go older. They still do—that’s apparent from the scatterplot that we showed earlier—but the reason that happens isn’t necessarily because of age. The coefficient for percent white is -0.682, which means a 1% increase in the proportion of whites in a county is associated with a decrease of 0.682 in the share of democratic votes, on average (e.g. moving from 40% to 39.318%).</p>
<p>State effects also explain what’s happening. The base case here is Alabama, so all state coefficients are compared to that. NOTICE ALSO that Alaska is missing. That’s because this dataset is missing lots of details about Alaska, like median age, percent white, etc. R drops out rows where any of the explanatory variables are missing, so Alaska disappears from this model. The interpretation of these state effects aren’t entirely useful here. Arizona had a 7.96% lower share of democratic votes than Alabama, controlling for age, race, income, and rent, on average. Arkansas had a 4.08% higher share of democratic votes than Alabama, controlling for age, race, income, and rent, on average. And so on, ad nauseum.</p>
<p>These coefficients are helpful because they filter out and account for state-related variation in vote share, but on their own they’re not super helpful. Because of that, we can actually omit them from our regression table with <code>filter()</code>:</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">get_regression_table</span>(model_lots_of_stuff) <span class="op">%&gt;%</span><span class="st"> </span>
<span class="st">  </span><span class="co"># str_detect looks inside a column to see if a specific string of text exists</span>
<span class="st">  </span><span class="co"># (in this case &quot;state&quot;). We negate it with ! so it&#39;ll only select rows where</span>
<span class="st">  </span><span class="co"># the phrase &quot;state&quot; isn&#39;t in it</span>
<span class="st">  </span><span class="kw">filter</span>(<span class="op">!</span><span class="kw">str_detect</span>(term, <span class="st">&quot;state&quot;</span>))</code></pre>
<pre><code>## # A tibble: 5 x 7
##   term              estimate std_error statistic p_value lower_ci upper_ci
##   &lt;chr&gt;                &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;   &lt;dbl&gt;    &lt;dbl&gt;    &lt;dbl&gt;
## 1 intercept           58.5       1.66      35.3        0   55.2     61.8  
## 2 median_age           0.166     0.037      4.52       0    0.094    0.238
## 3 percent_white       -0.682     0.011    -61.9        0   -0.704   -0.661
## 4 per_capita_income    0         0          5.46       0    0        0    
## 5 median_rent          0.02      0.002     12.3        0    0.017    0.023</code></pre>
<h4 id="all-models-side-by-side">All models side-by-side</h4>
<p>We can use the <code>huxreg()</code> function in the <code>huxtable</code> library to make a table where these models are shown in columns:</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">library</span>(huxtable)

<span class="co"># We don&#39;t want to include state coefficients, so here we make a list of all the</span>
<span class="co"># state coefficient names, then we tell huxreg() to ignore them</span>
state_coefs &lt;-<span class="st"> </span><span class="kw">tidy</span>(model_lots_of_stuff) <span class="op">%&gt;%</span><span class="st"> </span>
<span class="st">  </span><span class="kw">filter</span>(<span class="kw">str_detect</span>(term, <span class="st">&quot;state&quot;</span>)) <span class="op">%&gt;%</span><span class="st"> </span>
<span class="st">  </span><span class="kw">pull</span>(term)

<span class="kw">huxreg</span>(us_dem_age, model_age_dem_race, model_lots_of_stuff,
       <span class="dt">omit_coefs =</span> state_coefs) <span class="op">%&gt;%</span><span class="st"> </span>
<span class="st">  </span><span class="co"># This inserts a row named &quot;State controls&quot; at the bottom of the table marking</span>
<span class="st">  </span><span class="co"># whether or not we&#39;ve included state as an explanatory variable. We do this</span>
<span class="st">  </span><span class="co"># so we don&#39;t have to include 50 rows of state coefficients</span>
<span class="st">  </span><span class="kw">add_rows</span>(<span class="kw">hux</span>(<span class="st">&quot;State controls&quot;</span>, <span class="st">&quot;No&quot;</span>, <span class="st">&quot;No&quot;</span>, <span class="st">&quot;Yes&quot;</span>),
           <span class="dt">after =</span> <span class="kw">nrow</span>(.) <span class="op">-</span><span class="st"> </span><span class="dv">5</span>)</code></pre>
<table class="huxtable" style="border-collapse: collapse; margin-bottom: 2em; margin-top: 2em; width: 50%; margin-left: 0%; margin-right: auto;  ">
<col>
<col>
<col>
<col>
<tr>
<td style="vertical-align: top; text-align: center; white-space: nowrap; border-style: solid solid solid solid; border-width: 0.8pt 0pt 0pt 0pt; padding: 4pt 4pt 4pt 4pt;">
</td>
<td style="vertical-align: top; text-align: center; white-space: nowrap; border-style: solid solid solid solid; border-width: 0.8pt 0pt 0.4pt 0pt; padding: 4pt 4pt 4pt 4pt;">
(1)
</td>
<td style="vertical-align: top; text-align: center; white-space: nowrap; border-style: solid solid solid solid; border-width: 0.8pt 0pt 0.4pt 0pt; padding: 4pt 4pt 4pt 4pt;">
(2)
</td>
<td style="vertical-align: top; text-align: center; white-space: nowrap; border-style: solid solid solid solid; border-width: 0.8pt 0pt 0.4pt 0pt; padding: 4pt 4pt 4pt 4pt;">
(3)
</td>
</tr>
<tr>
<td style="vertical-align: top; text-align: left; white-space: nowrap; padding: 4pt 4pt 4pt 4pt;">
(Intercept)
</td>
<td style="vertical-align: top; text-align: right; white-space: nowrap; padding: 4pt 4pt 4pt 4pt;">
67.52 ***
</td>
<td style="vertical-align: top; text-align: right; white-space: nowrap; padding: 4pt 4pt 4pt 4pt;">
70.36 ***
</td>
<td style="vertical-align: top; text-align: right; white-space: nowrap; padding: 4pt 4pt 4pt 4pt;">
58.50 ***
</td>
</tr>
<tr>
<td style="vertical-align: top; text-align: left; white-space: nowrap; padding: 4pt 4pt 4pt 4pt;">
</td>
<td style="vertical-align: top; text-align: right; white-space: nowrap; padding: 4pt 4pt 4pt 4pt;">
(2.09)   
</td>
<td style="vertical-align: top; text-align: right; white-space: nowrap; padding: 4pt 4pt 4pt 4pt;">
(1.76)   
</td>
<td style="vertical-align: top; text-align: right; white-space: nowrap; padding: 4pt 4pt 4pt 4pt;">
(1.66)   
</td>
</tr>
<tr>
<td style="vertical-align: top; text-align: left; white-space: nowrap; padding: 4pt 4pt 4pt 4pt;">
median_age
</td>
<td style="vertical-align: top; text-align: right; white-space: nowrap; padding: 4pt 4pt 4pt 4pt;">
-0.89 ***
</td>
<td style="vertical-align: top; text-align: right; white-space: nowrap; padding: 4pt 4pt 4pt 4pt;">
-0.09    
</td>
<td style="vertical-align: top; text-align: right; white-space: nowrap; padding: 4pt 4pt 4pt 4pt;">
0.17 ***
</td>
</tr>
<tr>
<td style="vertical-align: top; text-align: left; white-space: nowrap; padding: 4pt 4pt 4pt 4pt;">
</td>
<td style="vertical-align: top; text-align: right; white-space: nowrap; padding: 4pt 4pt 4pt 4pt;">
(0.05)   
</td>
<td style="vertical-align: top; text-align: right; white-space: nowrap; padding: 4pt 4pt 4pt 4pt;">
(0.05)   
</td>
<td style="vertical-align: top; text-align: right; white-space: nowrap; padding: 4pt 4pt 4pt 4pt;">
(0.04)   
</td>
</tr>
<tr>
<td style="vertical-align: top; text-align: left; white-space: nowrap; padding: 4pt 4pt 4pt 4pt;">
percent_white
</td>
<td style="vertical-align: top; text-align: right; white-space: nowrap; padding: 4pt 4pt 4pt 4pt;">
       
</td>
<td style="vertical-align: top; text-align: right; white-space: nowrap; padding: 4pt 4pt 4pt 4pt;">
-0.45 ***
</td>
<td style="vertical-align: top; text-align: right; white-space: nowrap; padding: 4pt 4pt 4pt 4pt;">
-0.68 ***
</td>
</tr>
<tr>
<td style="vertical-align: top; text-align: left; white-space: nowrap; padding: 4pt 4pt 4pt 4pt;">
</td>
<td style="vertical-align: top; text-align: right; white-space: nowrap; padding: 4pt 4pt 4pt 4pt;">
       
</td>
<td style="vertical-align: top; text-align: right; white-space: nowrap; padding: 4pt 4pt 4pt 4pt;">
(0.01)   
</td>
<td style="vertical-align: top; text-align: right; white-space: nowrap; padding: 4pt 4pt 4pt 4pt;">
(0.01)   
</td>
</tr>
<tr>
<td style="vertical-align: top; text-align: left; white-space: nowrap; padding: 4pt 4pt 4pt 4pt;">
per_capita_income
</td>
<td style="vertical-align: top; text-align: right; white-space: nowrap; padding: 4pt 4pt 4pt 4pt;">
       
</td>
<td style="vertical-align: top; text-align: right; white-space: nowrap; padding: 4pt 4pt 4pt 4pt;">
       
</td>
<td style="vertical-align: top; text-align: right; white-space: nowrap; padding: 4pt 4pt 4pt 4pt;">
0.00 ***
</td>
</tr>
<tr>
<td style="vertical-align: top; text-align: left; white-space: nowrap; padding: 4pt 4pt 4pt 4pt;">
</td>
<td style="vertical-align: top; text-align: right; white-space: nowrap; padding: 4pt 4pt 4pt 4pt;">
       
</td>
<td style="vertical-align: top; text-align: right; white-space: nowrap; padding: 4pt 4pt 4pt 4pt;">
       
</td>
<td style="vertical-align: top; text-align: right; white-space: nowrap; padding: 4pt 4pt 4pt 4pt;">
(0.00)   
</td>
</tr>
<tr>
<td style="vertical-align: top; text-align: left; white-space: nowrap; padding: 4pt 4pt 4pt 4pt;">
median_rent
</td>
<td style="vertical-align: top; text-align: right; white-space: nowrap; padding: 4pt 4pt 4pt 4pt;">
       
</td>
<td style="vertical-align: top; text-align: right; white-space: nowrap; padding: 4pt 4pt 4pt 4pt;">
       
</td>
<td style="vertical-align: top; text-align: right; white-space: nowrap; padding: 4pt 4pt 4pt 4pt;">
0.02 ***
</td>
</tr>
<tr>
<td style="vertical-align: top; text-align: left; white-space: nowrap; padding: 4pt 4pt 4pt 4pt;">
</td>
<td style="vertical-align: top; text-align: right; white-space: nowrap; border-style: solid solid solid solid; border-width: 0pt 0pt 0.4pt 0pt; padding: 4pt 4pt 4pt 4pt;">
       
</td>
<td style="vertical-align: top; text-align: right; white-space: nowrap; border-style: solid solid solid solid; border-width: 0pt 0pt 0.4pt 0pt; padding: 4pt 4pt 4pt 4pt;">
       
</td>
<td style="vertical-align: top; text-align: right; white-space: nowrap; border-style: solid solid solid solid; border-width: 0pt 0pt 0.4pt 0pt; padding: 4pt 4pt 4pt 4pt;">
(0.00)   
</td>
</tr>
<tr>
<td style="vertical-align: top; text-align: left; white-space: nowrap; padding: 4pt 4pt 4pt 4pt;">
State controls
</td>
<td style="vertical-align: top; text-align: left; white-space: nowrap; padding: 4pt 4pt 4pt 4pt;">
No
</td>
<td style="vertical-align: top; text-align: left; white-space: nowrap; padding: 4pt 4pt 4pt 4pt;">
No
</td>
<td style="vertical-align: top; text-align: left; white-space: nowrap; padding: 4pt 4pt 4pt 4pt;">
Yes
</td>
</tr>
<tr>
<td style="vertical-align: top; text-align: left; white-space: nowrap; padding: 4pt 4pt 4pt 4pt;">
N
</td>
<td style="vertical-align: top; text-align: right; white-space: nowrap; padding: 4pt 4pt 4pt 4pt;">
3111       
</td>
<td style="vertical-align: top; text-align: right; white-space: nowrap; padding: 4pt 4pt 4pt 4pt;">
3111       
</td>
<td style="vertical-align: top; text-align: right; white-space: nowrap; padding: 4pt 4pt 4pt 4pt;">
3111       
</td>
</tr>
<tr>
<td style="vertical-align: top; text-align: left; white-space: nowrap; padding: 4pt 4pt 4pt 4pt;">
R2
</td>
<td style="vertical-align: top; text-align: right; white-space: nowrap; padding: 4pt 4pt 4pt 4pt;">
0.09    
</td>
<td style="vertical-align: top; text-align: right; white-space: nowrap; padding: 4pt 4pt 4pt 4pt;">
0.35    
</td>
<td style="vertical-align: top; text-align: right; white-space: nowrap; padding: 4pt 4pt 4pt 4pt;">
0.76    
</td>
</tr>
<tr>
<td style="vertical-align: top; text-align: left; white-space: nowrap; padding: 4pt 4pt 4pt 4pt;">
logLik
</td>
<td style="vertical-align: top; text-align: right; white-space: nowrap; padding: 4pt 4pt 4pt 4pt;">
-12746.87    
</td>
<td style="vertical-align: top; text-align: right; white-space: nowrap; padding: 4pt 4pt 4pt 4pt;">
-12221.27    
</td>
<td style="vertical-align: top; text-align: right; white-space: nowrap; padding: 4pt 4pt 4pt 4pt;">
-10678.35    
</td>
</tr>
<tr>
<td style="vertical-align: top; text-align: left; white-space: nowrap; border-style: solid solid solid solid; border-width: 0pt 0pt 0.8pt 0pt; padding: 4pt 4pt 4pt 4pt;">
AIC
</td>
<td style="vertical-align: top; text-align: right; white-space: nowrap; border-style: solid solid solid solid; border-width: 0pt 0pt 0.8pt 0pt; padding: 4pt 4pt 4pt 4pt;">
25499.73    
</td>
<td style="vertical-align: top; text-align: right; white-space: nowrap; border-style: solid solid solid solid; border-width: 0pt 0pt 0.8pt 0pt; padding: 4pt 4pt 4pt 4pt;">
24450.55    
</td>
<td style="vertical-align: top; text-align: right; white-space: nowrap; border-style: solid solid solid solid; border-width: 0pt 0pt 0.8pt 0pt; padding: 4pt 4pt 4pt 4pt;">
21466.70    
</td>
</tr>
<tr>
<td colspan="4" style="vertical-align: top; text-align: left; white-space: normal; padding: 4pt 4pt 4pt 4pt;">
*** p &lt; 0.001; ** p &lt; 0.01; * p &lt; 0.05.
</td>
</tr>
</table>
<h3 id="brexit">Brexit</h3>
<p>Now let’s explore variation in the 2016 Brexit vote results. Our main outcome variable (or y) is <code>leave_share</code>, which is the percent of votes cast in favor of leaving the European Union. Each row is a <a href="https://en.wikipedia.org/wiki/United_Kingdom_Parliament_constituencies">parliamentary constituency</a>. Again, to give you a sense of the spread of the data, here’s a histogram of the leave share in all constituencies:</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">ggplot</span>(results_brexit, <span class="kw">aes</span>(<span class="dt">x =</span> leave_share)) <span class="op">+</span>
<span class="st">  </span><span class="kw">geom_histogram</span>(<span class="dt">binwidth =</span> <span class="fl">2.5</span>)</code></pre>
<p><img src="/class/08-class_files/figure-html/dist-votes-uk-1.png" width="672" /></p>
<h4 id="leave-share-explained-by-immigration">Leave share explained by immigration</h4>
<p>One common explanation for the Brexit outcome is fear of immigration and the EU’s more open border policy. We can check the relationship between daily contact with immigrants and the propensity to vote to leave the EU by looking at the relationship between the proportion of native born residents in a constituency and its leave share.</p>
<pre class="sourceCode r"><code class="sourceCode r">results_brexit <span class="op">%&gt;%</span><span class="st"> </span>
<span class="st">  </span><span class="kw">get_correlation</span>(leave_share <span class="op">~</span><span class="st"> </span>born_in_uk)</code></pre>
<pre><code>## # A tibble: 1 x 1
##   correlation
##         &lt;dbl&gt;
## 1       0.493</code></pre>
<p>The correlation is almost 0.5, which shows that the two are fairly well positively correlated. As the proportion of native-born residents in a constituency goes up, the share of leave vote also goes up.</p>
<p>That’s apparent from the scatterplot too:</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">ggplot</span>(results_brexit, <span class="kw">aes</span>(<span class="dt">x =</span> born_in_uk, <span class="dt">y =</span> leave_share)) <span class="op">+</span>
<span class="st">  </span><span class="kw">geom_point</span>(<span class="dt">alpha =</span> <span class="fl">0.5</span>) <span class="op">+</span>
<span class="st">  </span><span class="kw">geom_smooth</span>(<span class="dt">method =</span> <span class="st">&quot;lm&quot;</span>)</code></pre>
<p><img src="/class/08-class_files/figure-html/leave-immigration-plot-1.png" width="672" /></p>
<p>A simple regression model will show us the slope, or the effect of immigrant populations on the share of leave votes:</p>
<pre class="sourceCode r"><code class="sourceCode r">brexit_leave_immigration &lt;-<span class="st"> </span><span class="kw">lm</span>(leave_share <span class="op">~</span><span class="st"> </span>born_in_uk, <span class="dt">data =</span> results_brexit)

<span class="kw">get_regression_table</span>(brexit_leave_immigration)</code></pre>
<pre><code>## # A tibble: 2 x 7
##   term       estimate std_error statistic p_value lower_ci upper_ci
##   &lt;chr&gt;         &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;   &lt;dbl&gt;    &lt;dbl&gt;    &lt;dbl&gt;
## 1 intercept      7.98     3.12       2.56   0.011    1.85    14.1  
## 2 born_in_uk     0.5      0.035     14.2    0        0.431    0.569</code></pre>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">get_regression_summaries</span>(brexit_leave_immigration)</code></pre>
<pre><code>## # A tibble: 1 x 8
##   r_squared adj_r_squared   mse  rmse sigma statistic p_value    df
##       &lt;dbl&gt;         &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;     &lt;dbl&gt;   &lt;dbl&gt; &lt;dbl&gt;
## 1     0.243         0.242  98.8  9.94  9.96      203.       0     2</code></pre>
<p>Interpretation time! The intercept shows what the average leave share would be in a constituency where 0% of the population was born in the UK. There are none of those—the most heavily immigrant-populated constituency is just over 40% native-born (see the scatterplot above). We can ignore the intercept.</p>
<p>The slope of born in the UK (<span class="math inline">\(\beta_1\)</span>) is 0.5, which means that a 1% increase in the proportion of native UK residents is associated with an increase in the leave vote share of 0.5, on average (e.g. moving from 50% leave to 50.5% leave).</p>
<p>The <span class="math inline">\(R^2\)</span> (the simple one, since we only have one explanatory variable) shows that this model explains 24.3% of the variation in leave votes.</p>
<h4 id="leave-share-explained-by-education-and-age">Leave share explained by education and age</h4>
<p>Another common explanation for the Brexit outcome is that it was driven by older people with less education. Let’s see if that checks out by using <code>degree</code> (which measures the percent of constituency’s population with a university degree) and <code>age_18to24</code> (which measures the percent of a constituency’s population between the ages of 18 and 24).</p>
<p>First we can check the relationships on their own. First, the correlation:</p>
<pre class="sourceCode r"><code class="sourceCode r">results_brexit <span class="op">%&gt;%</span><span class="st"> </span>
<span class="st">  </span><span class="co"># Some of these constituencies have missing data about education, so we remove</span>
<span class="st">  </span><span class="co"># rows where that&#39;s missing</span>
<span class="st">  </span><span class="kw">filter</span>(<span class="op">!</span><span class="kw">is.na</span>(degree), <span class="op">!</span><span class="kw">is.na</span>(leave_share)) <span class="op">%&gt;%</span><span class="st"> </span>
<span class="st">  </span><span class="kw">get_correlation</span>(leave_share <span class="op">~</span><span class="st"> </span>degree)</code></pre>
<pre><code>## # A tibble: 1 x 1
##   correlation
##         &lt;dbl&gt;
## 1      -0.906</code></pre>
<p>−0.9! That’s huge. The two are very strongly negatively correlated. As the education level of a constituency goes up, the share of leave votes goes down a ton. It’s very apparent in the plot too—all the points are very tightly clustered around the line:</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">ggplot</span>(results_brexit, <span class="kw">aes</span>(<span class="dt">x =</span> degree, <span class="dt">y =</span> leave_share)) <span class="op">+</span>
<span class="st">  </span><span class="kw">geom_point</span>() <span class="op">+</span>
<span class="st">  </span><span class="kw">geom_smooth</span>(<span class="dt">method =</span> <span class="st">&quot;lm&quot;</span>)</code></pre>
<p><img src="/class/08-class_files/figure-html/leave-education-plot-1.png" width="672" /></p>
<p>We can also check the correlation between leave votes and age:</p>
<pre class="sourceCode r"><code class="sourceCode r">results_brexit <span class="op">%&gt;%</span><span class="st"> </span>
<span class="st">  </span><span class="kw">get_correlation</span>(leave_share <span class="op">~</span><span class="st"> </span>age_18to24)</code></pre>
<pre><code>## # A tibble: 1 x 1
##   correlation
##         &lt;dbl&gt;
## 1      -0.347</code></pre>
<p>Age and leave votes are moderately negatively correlated (r = −0.35). Again, we can see this in the plot—the relationship is negative, but the points aren’t that tightly packed around the line. (Also this chart reads kind of backwards: as you go along the x-axis, constituencies are actually getting <em>younger</em>, since this is measuring the proportion of the county that is between 18 and 24. A greater proportion means more young kids.)</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">ggplot</span>(results_brexit, <span class="kw">aes</span>(<span class="dt">x =</span> age_18to24, <span class="dt">y =</span> leave_share)) <span class="op">+</span>
<span class="st">  </span><span class="kw">geom_point</span>() <span class="op">+</span>
<span class="st">  </span><span class="kw">geom_smooth</span>(<span class="dt">method =</span> <span class="st">&quot;lm&quot;</span>)</code></pre>
<p><img src="/class/08-class_files/figure-html/leave-age-plot-1.png" width="672" /></p>
<p>Let’s look at the effect of both of these on the leave share with a multiple regression model:</p>
<pre class="sourceCode r"><code class="sourceCode r">leave_educ_age &lt;-<span class="st"> </span><span class="kw">lm</span>(leave_share <span class="op">~</span><span class="st"> </span>degree <span class="op">+</span><span class="st"> </span>age_18to24, <span class="dt">data =</span> results_brexit)

<span class="kw">get_regression_table</span>(leave_educ_age)</code></pre>
<pre><code>## # A tibble: 3 x 7
##   term       estimate std_error statistic p_value lower_ci upper_ci
##   &lt;chr&gt;         &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;   &lt;dbl&gt;    &lt;dbl&gt;    &lt;dbl&gt;
## 1 intercept    76.5       0.558    137.         0   75.4     77.6  
## 2 degree       -1.12      0.022    -50.8        0   -1.17    -1.08 
## 3 age_18to24   -0.456     0.052     -8.85       0   -0.557   -0.355</code></pre>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">get_regression_summaries</span>(leave_educ_age)</code></pre>
<pre><code>## # A tibble: 1 x 8
##   r_squared adj_r_squared   mse  rmse sigma statistic p_value    df
##       &lt;dbl&gt;         &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;     &lt;dbl&gt;   &lt;dbl&gt; &lt;dbl&gt;
## 1     0.843         0.842  18.3  4.28  4.29     1528.       0     3</code></pre>
<p>If we take the age of a constituency into account, a 1% increase in the proportion of the constituency with a university degree is associated with a 1.12 point drop in the share of leave votes (e.g. moving from 50% leave to 48.88% leave). Similarly, controlling for education, a 1% increase in the proportion of the constituency that is between 18 and 24 years old is associated with a 0.456 point drop in the share of leave vote (e.g. moving from 50% leave to 49.54%).</p>
<p>Both age and education have a negative effect on leave votes—constituencies that are younger and more educated had far fewer leave votes, on average.</p>
<p>This model explains an astonishing 84.2% of the variation in leave votes.</p>
<h4 id="leave-share-explained-by-political-party">Leave share explained by political party</h4>
<p>One final common explanation for the Brexit outcome is the role that UKIP played (Boris Johnson’s party; a far-right, populist, anti-EU party). We can see the relationship between how strong of a presence UKIP has in a constituency (based on its vote share in the 2015 parliamentary elections) and leave share.</p>
<p>Here we can see the relationship between Labour votes, Conservative votes, and UKIP votes. (To plot three political parties at the same time, I use <code>gather()</code> to make a longer data frame with a column named <code>party</code> and a column named <code>party_pct</code>).</p>
<pre class="sourceCode r"><code class="sourceCode r">brexit_parties &lt;-<span class="st"> </span>results_brexit <span class="op">%&gt;%</span><span class="st"> </span>
<span class="st">  </span><span class="kw">gather</span>(party, party_pct, <span class="kw">c</span>(con_<span class="dv">2015</span>, lab_<span class="dv">2015</span>, ukip_<span class="dv">2015</span>))

<span class="kw">ggplot</span>(brexit_parties, <span class="kw">aes</span>(<span class="dt">x =</span> party_pct, <span class="dt">y =</span> leave_share, <span class="dt">color =</span> party)) <span class="op">+</span>
<span class="st">  </span><span class="kw">geom_point</span>(<span class="dt">alpha =</span> <span class="fl">0.25</span>) <span class="op">+</span>
<span class="st">  </span><span class="kw">geom_smooth</span>(<span class="dt">method =</span> <span class="st">&quot;lm&quot;</span>) <span class="op">+</span><span class="st"> </span>
<span class="st">  </span><span class="kw">theme</span>(<span class="dt">legend.position =</span> <span class="st">&quot;bottom&quot;</span>)</code></pre>
<p><img src="/class/08-class_files/figure-html/leave-party-plot-1.png" width="672" /></p>
<p>Holy cow look at that UKIP line. The points are densely packed around the line, meaning that there’s a very strong positive correlation—the more a constituency voted for UKIP in 2015, the more it voted to leave the EU in 2016.</p>
<p>Let’s look at the model to get the slopes (or effects):</p>
<pre class="sourceCode r"><code class="sourceCode r">leave_politics &lt;-<span class="st"> </span><span class="kw">lm</span>(leave_share <span class="op">~</span><span class="st"> </span>con_<span class="dv">2015</span> <span class="op">+</span><span class="st"> </span>lab_<span class="dv">2015</span> <span class="op">+</span><span class="st"> </span>ukip_<span class="dv">2015</span>, 
                     <span class="dt">data =</span> results_brexit)

<span class="kw">get_regression_table</span>(leave_politics)</code></pre>
<pre><code>## # A tibble: 4 x 7
##   term      estimate std_error statistic p_value lower_ci upper_ci
##   &lt;chr&gt;        &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;   &lt;dbl&gt;    &lt;dbl&gt;    &lt;dbl&gt;
## 1 intercept   33.1       1.24     26.7     0       30.7     35.5  
## 2 con_2015     0.007     0.02      0.322   0.747   -0.034    0.047
## 3 lab_2015    -0.026     0.019    -1.32    0.188   -0.064    0.013
## 4 ukip_2015    1.49      0.039    38.0     0        1.41     1.57</code></pre>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">get_regression_summaries</span>(leave_politics)</code></pre>
<pre><code>## # A tibble: 1 x 8
##   r_squared adj_r_squared   mse  rmse sigma statistic p_value    df
##       &lt;dbl&gt;         &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;     &lt;dbl&gt;   &lt;dbl&gt; &lt;dbl&gt;
## 1      0.72         0.718  36.6  6.05  6.07      538.       0     4</code></pre>
<p>Interpretation time. Here we go.</p>
<p>Controlling for a constituency’s Labour and UKIP voting patterns, a 1% increase in the votes cast for the Conservative party in 2015 is associated with a 0.007 point increase in the share of leave votes on, average (e.g. moving from 50% to 50.007%), which is pretty much a sign that there’s no effect. Controlling for a constituency’s Conservative and UKIP voting patterns, a 1% increase in the votes cast for the Labour party in 2015 is associated with a 0.026 point drop in the share of leave votes, on average (e.g. moving from 50% to 49.97%). Labour constituencies were less likely to vote to leave, but only slightly. However, taking into account Labour and Conservative voting patterns, a 1% increase in the votes cast for UKIP in 2015 is associated with a 1.49 point increase in the share of leave votes (e.g. moving from 50% to 51.49%), which is quite a sizable effect.</p>
<p>This model explains 71.8% of the variation in the share of leave votes, which is pretty good. Just knowing how much of a presence UKIP has in a constituency is a good predictor of how it voted in the Brexit referendum.</p>
<h4 id="leave-share-explained-by-lots-of-things">Leave share explained by lots of things</h4>
<p>So far we’ve looked at immigration, education, age, and political party as explanations of the Brexit vote. How do these explanations change when we account for all these factors at once?</p>
<p>First, let’s run a big model:</p>
<pre class="sourceCode r"><code class="sourceCode r">leave_everything &lt;-<span class="st"> </span><span class="kw">lm</span>(leave_share <span class="op">~</span><span class="st"> </span>con_<span class="dv">2015</span> <span class="op">+</span><span class="st"> </span>lab_<span class="dv">2015</span> <span class="op">+</span><span class="st"> </span>ukip_<span class="dv">2015</span> <span class="op">+</span>
<span class="st">                         </span>degree <span class="op">+</span><span class="st"> </span>age_18to24 <span class="op">+</span><span class="st"> </span>born_in_uk, <span class="dt">data =</span> results_brexit)

<span class="kw">get_regression_table</span>(leave_everything)</code></pre>
<pre><code>## # A tibble: 7 x 7
##   term       estimate std_error statistic p_value lower_ci upper_ci
##   &lt;chr&gt;         &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;   &lt;dbl&gt;    &lt;dbl&gt;    &lt;dbl&gt;
## 1 intercept    56.4       2.64      21.4    0       51.2     61.6  
## 2 con_2015      0.155     0.017      9.38   0        0.123    0.188
## 3 lab_2015      0.059     0.015      3.84   0        0.029    0.09 
## 4 ukip_2015     0.713     0.038     18.9    0        0.639    0.787
## 5 degree       -0.87      0.029    -29.6    0       -0.928   -0.813
## 6 age_18to24   -0.196     0.044     -4.43   0       -0.283   -0.109
## 7 born_in_uk   -0.054     0.018     -3.08   0.002   -0.088   -0.019</code></pre>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">get_regression_summaries</span>(leave_everything)</code></pre>
<pre><code>## # A tibble: 1 x 8
##   r_squared adj_r_squared   mse  rmse sigma statistic p_value    df
##       &lt;dbl&gt;         &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;     &lt;dbl&gt;   &lt;dbl&gt; &lt;dbl&gt;
## 1     0.915         0.914  9.94  3.15  3.17     1012.       0     7</code></pre>
<p>I’ll interpret all the coefficients here so that you can get more practice reading these tables. In real life, you’d probably only be concerned about one or two of the explanatory variables (i.e. if you were only looking at the effect of age and education on leave vote share), so you’d only need to interpret those. The other control variables are essential—they explain part of the variation in vote share, and they let us isolate the effect of individual variables—but they don’t always have to be interpreted in your text in sentences.</p>
<p><deep breath></p>
<ul>
<li>Taking into account Labour and UKIP voting patterns, education, age, and immigration patterns, a 1% increase in the votes cast for the Conservative party in 2015 is associated with a 0.155 point increase in the share of leave votes in a constituency, on average (e.g. moving from 50% to 50.155%). This shows that Conservative constituencies tended to lean more towards “Leave”, but only slightly.</li>
<li>Controlling for Conservative and UKIP voting patterns, education, age, and immigration patterns, a 1% increase in 2015 Labour votes is associated with a 0.059 point increase in the share of leave votes, on average. This shows that (surprisingly) Labour constituencies also tended to lean towards “Leave”, but only very slightly (e.g. moving from 50% to 50.06%).</li>
<li>Controlling for Labour and Conservative voting patterns, education, age, and immigration patterns, a 1% increase in 2015 UKIP votes is associated with a 0.713 point increase in the share of leave votes in a constituency, on average. This shows that UKIP constituencies were a lot more likely to vote to leave, and that UKIP turnout is a pretty good predictor of voting to leave</li>
<li>Taking political party, age, and immigration patterns into account, a 1% increase in the proportion of a constituency with a university degree is associated with a 0.87 point drop in the share of leave votes (e.g. moving from 50% to 49.13%). After taking other factors into account, education is a great predictor of voting to leave.</li>
<li>Controlling for political party, education, and immigration patterns, a 1% increase in the proportion of a constituency between the ages of 18 and 24 is associated with a 0.196 point drop in the share of leave votes, on average. As constituencies becomes younger, they’re less likely to vote to leave the EU.</li>
<li><em>Finally</em>, taking into account political party, education, and age, a 1% increase in the proportion of native-born residents is associated with a 0.054 point drop in the share of leave votes (e.g. moving from 50% to 50.05%), which is not a huge effect (it’s the same size as the Labour Party effect, only in reverse). It also goes opposite to our intuition—once we account for all these other factors, more native-heavy constituencies are actually <em>less</em> likely to vote to leave (but only slightly so).</li>
</ul>
<p>In the end, the factors that made the biggest difference in Brexit vote outcomes appear to be UKIP voting and education, followed by age and Conservative voting.</p>
<p>According to the adjusted <span class="math inline">\(R^2\)</span>, this big model explains 91.4% of the variation in the proportion of leave votes in British parliamentary constituencies. That’s a fantastic model!</p>
<h4 id="making-predictions">Making predictions</h4>
<p>We didn’t have time to cover this in class this week, but we will later. We can plug values into this model equation and get a predicted <span class="math inline">\(\hat{y}\)</span>. What would we guess the leave vote share to be in a constituency that looks like this?</p>
<ul>
<li>The Conservative party won 40% of the vote in 2015</li>
<li>Labour won 30%</li>
<li>UKIP won 15%</li>
<li>20% of the constituency has a university degree</li>
<li>10% of the constituency is between 18 and 24</li>
<li>90% of the constituency was born in the UK</li>
</ul>
<p>We could do this by hand by plugging these into the equation that we get from the model. Here’s the model we ran:</p>
<p><span class="math display">\[
\begin{align}
\widehat{\text{leave share}} &amp;= \beta_0 + \beta_1 \text{Conservative}_{2015} + \beta_2 \text{Labour}_{2015} + \beta_3 \text{UKIP}_{2015} \\
&amp; + \beta_4 \text{degree} + \beta_5 \text{age 18 to 24} + \beta_6 \text{born in the UK} + \epsilon
\end{align}
\]</span></p>
<p>And here’s that model with the coefficients we estimated with the model:</p>
<p><span class="math display">\[
\begin{align}
\widehat{\text{leave share}} &amp;= 56.4 + (0.155 \times \text{Conservative}_{2015}) + (0.059 \times \text{Labour}_{2015}) + (0.713 \times \text{UKIP}_{2015}) \\
&amp; + (-0.87 \times \text{degree}) + (-0.196 \times \text{age 18 to 24}) + (-0.054 \times \text{born in the UK}) + \epsilon
\end{align}
\]</span></p>
<p>If we plug these hypothetical numbers into the equation, we’ll get a predicted <span class="math inline">\(\widehat{\text{leave share}}\)</span>:</p>
<p><span class="math display">\[
\begin{align}
\widehat{\text{leave share}} &amp;= 56.4 + (0.155 \times 40) + (0.059 \times 30) + (0.713 \times 15) \\
&amp; + (-0.87 \times 20) + (-0.196 \times 10) + (-0.054 \times 90) + \epsilon
\end{align}
\]</span></p>
<p>That’s a lot of math and I don’t want to do it by hand. Instead, we can use the <code>predict()</code> function in R to plug in a bunch of values and get the predicted leave share. First, we create a data frame with columns for each of the explanatory variables, then we use <code>predict(model_name, imaginary_constituency)</code> to generate <span class="math inline">\(\hat{y}\)</span>. We use the <code>interval = "prediction"</code> to generate a 95% prediction interval that shows how certain we can be about the prediction.</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="co"># Here&#39;s the imaginary constituency</span>
imaginary_constituency1 &lt;-<span class="st"> </span><span class="kw">tibble</span>(<span class="dt">con_2015 =</span> <span class="dv">40</span>,
                                  <span class="dt">lab_2015 =</span> <span class="dv">30</span>,
                                  <span class="dt">ukip_2015 =</span> <span class="dv">15</span>,
                                  <span class="dt">degree =</span> <span class="dv">20</span>,
                                  <span class="dt">age_18to24 =</span> <span class="dv">10</span>,
                                  <span class="dt">born_in_uk =</span> <span class="dv">90</span>)

<span class="co"># Here we predict leave vote share with the big model that we built, based on</span>
<span class="co"># the imaginary constituency that we invented above</span>
<span class="kw">predict</span>(leave_everything, <span class="dt">newdata =</span> imaginary_constituency1, <span class="dt">interval =</span> <span class="st">&quot;prediction&quot;</span>)</code></pre>
<pre><code>##        fit      lwr      upr
## 1 50.84641 44.60334 57.08948</code></pre>
<p>A constituency that looked like that would have likely had 50.85% voting for leaving the EU (with a 95% range of 45% to 57%).</p>
<p>What about a more Labour-heavy, younger, more educated constituency with more immigrants?</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="co"># Here&#39;s another imaginary constituency</span>
imaginary_constituency2 &lt;-<span class="st"> </span><span class="kw">tibble</span>(<span class="dt">con_2015 =</span> <span class="dv">20</span>,
                                  <span class="dt">lab_2015 =</span> <span class="dv">50</span>,
                                  <span class="dt">ukip_2015 =</span> <span class="dv">15</span>,
                                  <span class="dt">degree =</span> <span class="dv">40</span>,
                                  <span class="dt">age_18to24 =</span> <span class="dv">30</span>,
                                  <span class="dt">born_in_uk =</span> <span class="dv">80</span>)

<span class="co"># Here we predict leave vote share with the big model that we built, based on</span>
<span class="co"># the imaginary constituency that we invented above</span>
<span class="kw">predict</span>(leave_everything, <span class="dt">newdata =</span> imaginary_constituency2, <span class="dt">interval =</span> <span class="st">&quot;prediction&quot;</span>)</code></pre>
<pre><code>##        fit      lwr      upr
## 1 28.13658 21.57934 34.69381</code></pre>
<p>Only 28% would have voted to leave (with a 95% interval of 22% to 35%). That’s low, but it makes sense given the effects we saw in the regression model.</p>
<p>Finally, one last cool thing we can do with predictions is move one of these explanatory variables up and down while holding everything else constant in order to visually see what happens as the value changes.</p>
<p>So, for instance, let’s imagine an average constituency with these characteristics (these are roughly the actual averages):</p>
<ul>
<li>The Conservative party won 40% of the vote in 2015</li>
<li>Labour won 30%</li>
<li>UKIP won 15%</li>
<li>10% of the constituency is between 18 and 24</li>
<li>90% of the constituency was born in the UK</li>
</ul>
<p>We want to see the the effect of education. What happens if the proportion of the constituency with a university degree is 10%? 20%? 30%? 40%? etc. What happens to the leave share as we move this education up and down?</p>
<p>We can answer this by creating an <code>imaginary_constituency</code> data frame with multiple rows, varying education in each one. We then plug that data frame into <code>predict()</code> and generate predictions for each row.</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="co"># Here are six imaginary constituencies, all with the same variables except</span>
<span class="co"># education, which goes up by five in each row</span>
imaginary_constituency3 &lt;-<span class="st"> </span><span class="kw">tibble</span>(<span class="dt">con_2015 =</span> <span class="dv">20</span>,
                                  <span class="dt">lab_2015 =</span> <span class="dv">50</span>,
                                  <span class="dt">ukip_2015 =</span> <span class="dv">15</span>,
                                  <span class="dt">degree =</span> <span class="kw">c</span>(<span class="dv">5</span>, <span class="dv">10</span>, <span class="dv">15</span>, <span class="dv">20</span>, <span class="dv">25</span>, <span class="dv">30</span>),
                                  <span class="dt">age_18to24 =</span> <span class="dv">30</span>,
                                  <span class="dt">born_in_uk =</span> <span class="dv">80</span>)
imaginary_constituency3</code></pre>
<pre><code>## # A tibble: 6 x 6
##   con_2015 lab_2015 ukip_2015 degree age_18to24 born_in_uk
##      &lt;dbl&gt;    &lt;dbl&gt;     &lt;dbl&gt;  &lt;dbl&gt;      &lt;dbl&gt;      &lt;dbl&gt;
## 1       20       50        15      5         30         80
## 2       20       50        15     10         30         80
## 3       20       50        15     15         30         80
## 4       20       50        15     20         30         80
## 5       20       50        15     25         30         80
## 6       20       50        15     30         30         80</code></pre>
<pre class="sourceCode r"><code class="sourceCode r"><span class="co"># When we plug this multi-row data frame into predict(), it&#39;ll generate a</span>
<span class="co"># prediction for each row</span>
<span class="kw">predict</span>(leave_everything, <span class="dt">newdata =</span> imaginary_constituency3, <span class="dt">interval =</span> <span class="st">&quot;prediction&quot;</span>)</code></pre>
<pre><code>##        fit      lwr      upr
## 1 58.60227 52.09952 65.10502
## 2 54.25003 47.77813 60.72193
## 3 49.89779 43.44391 56.35166
## 4 45.54555 39.09676 51.99433
## 5 41.19330 34.73664 47.64996
## 6 36.84106 30.36361 43.31852</code></pre>
<p>When an average constituency has only 5% of people with degrees, the predicted leave share is 58.6%. As the proportion of people with degrees goes up, the predicted leave share drops quite a lot. By the time we get to 30% with degrees, the predicted leave share is 36.8%.</p>
<p>We can visualize this change too, to make it more apparent than just looking at a table of numbers. Look how steep that slope is!</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="co"># Here, instead of using predict(), I use augment() from the broom package. It&#39;s</span>
<span class="co"># essentially the same thing as predict, but it adds the predictions and</span>
<span class="co"># confidence intervals to the imaginary constituency data frame</span>
model_predictions &lt;-<span class="st"> </span><span class="kw">augment</span>(leave_everything, 
                             <span class="dt">newdata =</span> imaginary_constituency3)

<span class="co"># Now we have two new columns named .fitted and .se.fit: .fitted is the</span>
<span class="co"># predicted value and .se.fit is the standard error of the predicted value</span>
model_predictions</code></pre>
<pre><code>## # A tibble: 6 x 8
##   con_2015 lab_2015 ukip_2015 degree age_18to24 born_in_uk .fitted .se.fit
##      &lt;dbl&gt;    &lt;dbl&gt;     &lt;dbl&gt;  &lt;dbl&gt;      &lt;dbl&gt;      &lt;dbl&gt;   &lt;dbl&gt;   &lt;dbl&gt;
## 1       20       50        15      5         30         80    58.6   0.945
## 2       20       50        15     10         30         80    54.3   0.888
## 3       20       50        15     15         30         80    49.9   0.854
## 4       20       50        15     20         30         80    45.5   0.844
## 5       20       50        15     25         30         80    41.2   0.859
## 6       20       50        15     30         30         80    36.8   0.899</code></pre>
<pre class="sourceCode r"><code class="sourceCode r"><span class="co"># We can plot this now:</span>
<span class="kw">ggplot</span>(model_predictions, <span class="kw">aes</span>(<span class="dt">x =</span> degree, <span class="dt">y =</span> .fitted)) <span class="op">+</span>
<span class="st">  </span><span class="kw">geom_line</span>() <span class="op">+</span>
<span class="st">  </span><span class="kw">labs</span>(<span class="dt">y =</span> <span class="st">&quot;Predicted leave share&quot;</span>, 
       <span class="dt">x =</span> <span class="st">&quot;Proportion of constituency with a university degree&quot;</span>)</code></pre>
<p><img src="/class/08-class_files/figure-html/plot-brexit-predict-1.png" width="672" /></p>
<p>With one final mathy tweak, we can add 95% confidence intervals to this line. We haven’t covered confidence intervals yet, but we will.</p>
<pre class="sourceCode r"><code class="sourceCode r">model_predictions_with_intervals &lt;-<span class="st"> </span>model_predictions <span class="op">%&gt;%</span><span class="st"> </span>
<span class="st">  </span><span class="kw">mutate</span>(<span class="dt">conf_low =</span> .fitted <span class="op">+</span><span class="st"> </span>(<span class="fl">1.96</span> <span class="op">*</span><span class="st"> </span>.se.fit),
         <span class="dt">conf_high =</span> .fitted <span class="op">-</span><span class="st"> </span>(<span class="fl">1.96</span> <span class="op">*</span><span class="st"> </span>.se.fit))

<span class="kw">ggplot</span>(model_predictions_with_intervals, <span class="kw">aes</span>(<span class="dt">x =</span> degree, <span class="dt">y =</span> .fitted)) <span class="op">+</span>
<span class="st">  </span><span class="kw">geom_ribbon</span>(<span class="kw">aes</span>(<span class="dt">ymin =</span> conf_low, <span class="dt">ymax =</span> conf_high), <span class="dt">alpha =</span> <span class="fl">0.25</span>) <span class="op">+</span>
<span class="st">  </span><span class="kw">geom_line</span>() <span class="op">+</span>
<span class="st">  </span><span class="kw">labs</span>(<span class="dt">y =</span> <span class="st">&quot;Predicted leave share&quot;</span>, 
       <span class="dt">x =</span> <span class="st">&quot;Proportion of constituency with a university degree&quot;</span>)</code></pre>
<p><img src="/class/08-class_files/figure-html/plot-brexit-predict-intervalse-1.png" width="672" /></p>
<h4 id="all-models-side-by-side-1">All models side-by-side</h4>
<p>Like we did before, we can use <code>huxreg()</code> to view all these models side-by-side and compare the coefficients and the <span class="math inline">\(R^2\)</span> values:</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">huxreg</span>(brexit_leave_immigration, leave_educ_age, 
       leave_politics, leave_everything) </code></pre>
<table class="huxtable" style="border-collapse: collapse; margin-bottom: 2em; margin-top: 2em; width: 50%; margin-left: 0%; margin-right: auto;  ">
<col>
<col>
<col>
<col>
<col>
<tr>
<td style="vertical-align: top; text-align: center; white-space: nowrap; border-style: solid solid solid solid; border-width: 0.8pt 0pt 0pt 0pt; padding: 4pt 4pt 4pt 4pt;">
</td>
<td style="vertical-align: top; text-align: center; white-space: nowrap; border-style: solid solid solid solid; border-width: 0.8pt 0pt 0.4pt 0pt; padding: 4pt 4pt 4pt 4pt;">
(1)
</td>
<td style="vertical-align: top; text-align: center; white-space: nowrap; border-style: solid solid solid solid; border-width: 0.8pt 0pt 0.4pt 0pt; padding: 4pt 4pt 4pt 4pt;">
(2)
</td>
<td style="vertical-align: top; text-align: center; white-space: nowrap; border-style: solid solid solid solid; border-width: 0.8pt 0pt 0.4pt 0pt; padding: 4pt 4pt 4pt 4pt;">
(3)
</td>
<td style="vertical-align: top; text-align: center; white-space: nowrap; border-style: solid solid solid solid; border-width: 0.8pt 0pt 0.4pt 0pt; padding: 4pt 4pt 4pt 4pt;">
(4)
</td>
</tr>
<tr>
<td style="vertical-align: top; text-align: left; white-space: nowrap; padding: 4pt 4pt 4pt 4pt;">
(Intercept)
</td>
<td style="vertical-align: top; text-align: right; white-space: nowrap; padding: 4pt 4pt 4pt 4pt;">
7.98 *  
</td>
<td style="vertical-align: top; text-align: right; white-space: nowrap; padding: 4pt 4pt 4pt 4pt;">
76.51 ***
</td>
<td style="vertical-align: top; text-align: right; white-space: nowrap; padding: 4pt 4pt 4pt 4pt;">
33.10 ***
</td>
<td style="vertical-align: top; text-align: right; white-space: nowrap; padding: 4pt 4pt 4pt 4pt;">
56.38 ***
</td>
</tr>
<tr>
<td style="vertical-align: top; text-align: left; white-space: nowrap; padding: 4pt 4pt 4pt 4pt;">
</td>
<td style="vertical-align: top; text-align: right; white-space: nowrap; padding: 4pt 4pt 4pt 4pt;">
(3.12)   
</td>
<td style="vertical-align: top; text-align: right; white-space: nowrap; padding: 4pt 4pt 4pt 4pt;">
(0.56)   
</td>
<td style="vertical-align: top; text-align: right; white-space: nowrap; padding: 4pt 4pt 4pt 4pt;">
(1.24)   
</td>
<td style="vertical-align: top; text-align: right; white-space: nowrap; padding: 4pt 4pt 4pt 4pt;">
(2.64)   
</td>
</tr>
<tr>
<td style="vertical-align: top; text-align: left; white-space: nowrap; padding: 4pt 4pt 4pt 4pt;">
born_in_uk
</td>
<td style="vertical-align: top; text-align: right; white-space: nowrap; padding: 4pt 4pt 4pt 4pt;">
0.50 ***
</td>
<td style="vertical-align: top; text-align: right; white-space: nowrap; padding: 4pt 4pt 4pt 4pt;">
       
</td>
<td style="vertical-align: top; text-align: right; white-space: nowrap; padding: 4pt 4pt 4pt 4pt;">
       
</td>
<td style="vertical-align: top; text-align: right; white-space: nowrap; padding: 4pt 4pt 4pt 4pt;">
-0.05 ** 
</td>
</tr>
<tr>
<td style="vertical-align: top; text-align: left; white-space: nowrap; padding: 4pt 4pt 4pt 4pt;">
</td>
<td style="vertical-align: top; text-align: right; white-space: nowrap; padding: 4pt 4pt 4pt 4pt;">
(0.04)   
</td>
<td style="vertical-align: top; text-align: right; white-space: nowrap; padding: 4pt 4pt 4pt 4pt;">
       
</td>
<td style="vertical-align: top; text-align: right; white-space: nowrap; padding: 4pt 4pt 4pt 4pt;">
       
</td>
<td style="vertical-align: top; text-align: right; white-space: nowrap; padding: 4pt 4pt 4pt 4pt;">
(0.02)   
</td>
</tr>
<tr>
<td style="vertical-align: top; text-align: left; white-space: nowrap; padding: 4pt 4pt 4pt 4pt;">
degree
</td>
<td style="vertical-align: top; text-align: right; white-space: nowrap; padding: 4pt 4pt 4pt 4pt;">
       
</td>
<td style="vertical-align: top; text-align: right; white-space: nowrap; padding: 4pt 4pt 4pt 4pt;">
-1.13 ***
</td>
<td style="vertical-align: top; text-align: right; white-space: nowrap; padding: 4pt 4pt 4pt 4pt;">
       
</td>
<td style="vertical-align: top; text-align: right; white-space: nowrap; padding: 4pt 4pt 4pt 4pt;">
-0.87 ***
</td>
</tr>
<tr>
<td style="vertical-align: top; text-align: left; white-space: nowrap; padding: 4pt 4pt 4pt 4pt;">
</td>
<td style="vertical-align: top; text-align: right; white-space: nowrap; padding: 4pt 4pt 4pt 4pt;">
       
</td>
<td style="vertical-align: top; text-align: right; white-space: nowrap; padding: 4pt 4pt 4pt 4pt;">
(0.02)   
</td>
<td style="vertical-align: top; text-align: right; white-space: nowrap; padding: 4pt 4pt 4pt 4pt;">
       
</td>
<td style="vertical-align: top; text-align: right; white-space: nowrap; padding: 4pt 4pt 4pt 4pt;">
(0.03)   
</td>
</tr>
<tr>
<td style="vertical-align: top; text-align: left; white-space: nowrap; padding: 4pt 4pt 4pt 4pt;">
age_18to24
</td>
<td style="vertical-align: top; text-align: right; white-space: nowrap; padding: 4pt 4pt 4pt 4pt;">
       
</td>
<td style="vertical-align: top; text-align: right; white-space: nowrap; padding: 4pt 4pt 4pt 4pt;">
-0.46 ***
</td>
<td style="vertical-align: top; text-align: right; white-space: nowrap; padding: 4pt 4pt 4pt 4pt;">
       
</td>
<td style="vertical-align: top; text-align: right; white-space: nowrap; padding: 4pt 4pt 4pt 4pt;">
-0.20 ***
</td>
</tr>
<tr>
<td style="vertical-align: top; text-align: left; white-space: nowrap; padding: 4pt 4pt 4pt 4pt;">
</td>
<td style="vertical-align: top; text-align: right; white-space: nowrap; padding: 4pt 4pt 4pt 4pt;">
       
</td>
<td style="vertical-align: top; text-align: right; white-space: nowrap; padding: 4pt 4pt 4pt 4pt;">
(0.05)   
</td>
<td style="vertical-align: top; text-align: right; white-space: nowrap; padding: 4pt 4pt 4pt 4pt;">
       
</td>
<td style="vertical-align: top; text-align: right; white-space: nowrap; padding: 4pt 4pt 4pt 4pt;">
(0.04)   
</td>
</tr>
<tr>
<td style="vertical-align: top; text-align: left; white-space: nowrap; padding: 4pt 4pt 4pt 4pt;">
con_2015
</td>
<td style="vertical-align: top; text-align: right; white-space: nowrap; padding: 4pt 4pt 4pt 4pt;">
       
</td>
<td style="vertical-align: top; text-align: right; white-space: nowrap; padding: 4pt 4pt 4pt 4pt;">
       
</td>
<td style="vertical-align: top; text-align: right; white-space: nowrap; padding: 4pt 4pt 4pt 4pt;">
0.01    
</td>
<td style="vertical-align: top; text-align: right; white-space: nowrap; padding: 4pt 4pt 4pt 4pt;">
0.16 ***
</td>
</tr>
<tr>
<td style="vertical-align: top; text-align: left; white-space: nowrap; padding: 4pt 4pt 4pt 4pt;">
</td>
<td style="vertical-align: top; text-align: right; white-space: nowrap; padding: 4pt 4pt 4pt 4pt;">
       
</td>
<td style="vertical-align: top; text-align: right; white-space: nowrap; padding: 4pt 4pt 4pt 4pt;">
       
</td>
<td style="vertical-align: top; text-align: right; white-space: nowrap; padding: 4pt 4pt 4pt 4pt;">
(0.02)   
</td>
<td style="vertical-align: top; text-align: right; white-space: nowrap; padding: 4pt 4pt 4pt 4pt;">
(0.02)   
</td>
</tr>
<tr>
<td style="vertical-align: top; text-align: left; white-space: nowrap; padding: 4pt 4pt 4pt 4pt;">
lab_2015
</td>
<td style="vertical-align: top; text-align: right; white-space: nowrap; padding: 4pt 4pt 4pt 4pt;">
       
</td>
<td style="vertical-align: top; text-align: right; white-space: nowrap; padding: 4pt 4pt 4pt 4pt;">
       
</td>
<td style="vertical-align: top; text-align: right; white-space: nowrap; padding: 4pt 4pt 4pt 4pt;">
-0.03    
</td>
<td style="vertical-align: top; text-align: right; white-space: nowrap; padding: 4pt 4pt 4pt 4pt;">
0.06 ***
</td>
</tr>
<tr>
<td style="vertical-align: top; text-align: left; white-space: nowrap; padding: 4pt 4pt 4pt 4pt;">
</td>
<td style="vertical-align: top; text-align: right; white-space: nowrap; padding: 4pt 4pt 4pt 4pt;">
       
</td>
<td style="vertical-align: top; text-align: right; white-space: nowrap; padding: 4pt 4pt 4pt 4pt;">
       
</td>
<td style="vertical-align: top; text-align: right; white-space: nowrap; padding: 4pt 4pt 4pt 4pt;">
(0.02)   
</td>
<td style="vertical-align: top; text-align: right; white-space: nowrap; padding: 4pt 4pt 4pt 4pt;">
(0.02)   
</td>
</tr>
<tr>
<td style="vertical-align: top; text-align: left; white-space: nowrap; padding: 4pt 4pt 4pt 4pt;">
ukip_2015
</td>
<td style="vertical-align: top; text-align: right; white-space: nowrap; padding: 4pt 4pt 4pt 4pt;">
       
</td>
<td style="vertical-align: top; text-align: right; white-space: nowrap; padding: 4pt 4pt 4pt 4pt;">
       
</td>
<td style="vertical-align: top; text-align: right; white-space: nowrap; padding: 4pt 4pt 4pt 4pt;">
1.49 ***
</td>
<td style="vertical-align: top; text-align: right; white-space: nowrap; padding: 4pt 4pt 4pt 4pt;">
0.71 ***
</td>
</tr>
<tr>
<td style="vertical-align: top; text-align: left; white-space: nowrap; padding: 4pt 4pt 4pt 4pt;">
</td>
<td style="vertical-align: top; text-align: right; white-space: nowrap; border-style: solid solid solid solid; border-width: 0pt 0pt 0.4pt 0pt; padding: 4pt 4pt 4pt 4pt;">
       
</td>
<td style="vertical-align: top; text-align: right; white-space: nowrap; border-style: solid solid solid solid; border-width: 0pt 0pt 0.4pt 0pt; padding: 4pt 4pt 4pt 4pt;">
       
</td>
<td style="vertical-align: top; text-align: right; white-space: nowrap; border-style: solid solid solid solid; border-width: 0pt 0pt 0.4pt 0pt; padding: 4pt 4pt 4pt 4pt;">
(0.04)   
</td>
<td style="vertical-align: top; text-align: right; white-space: nowrap; border-style: solid solid solid solid; border-width: 0pt 0pt 0.4pt 0pt; padding: 4pt 4pt 4pt 4pt;">
(0.04)   
</td>
</tr>
<tr>
<td style="vertical-align: top; text-align: left; white-space: nowrap; padding: 4pt 4pt 4pt 4pt;">
N
</td>
<td style="vertical-align: top; text-align: right; white-space: nowrap; padding: 4pt 4pt 4pt 4pt;">
632       
</td>
<td style="vertical-align: top; text-align: right; white-space: nowrap; padding: 4pt 4pt 4pt 4pt;">
573       
</td>
<td style="vertical-align: top; text-align: right; white-space: nowrap; padding: 4pt 4pt 4pt 4pt;">
632       
</td>
<td style="vertical-align: top; text-align: right; white-space: nowrap; padding: 4pt 4pt 4pt 4pt;">
573       
</td>
</tr>
<tr>
<td style="vertical-align: top; text-align: left; white-space: nowrap; padding: 4pt 4pt 4pt 4pt;">
R2
</td>
<td style="vertical-align: top; text-align: right; white-space: nowrap; padding: 4pt 4pt 4pt 4pt;">
0.24    
</td>
<td style="vertical-align: top; text-align: right; white-space: nowrap; padding: 4pt 4pt 4pt 4pt;">
0.84    
</td>
<td style="vertical-align: top; text-align: right; white-space: nowrap; padding: 4pt 4pt 4pt 4pt;">
0.72    
</td>
<td style="vertical-align: top; text-align: right; white-space: nowrap; padding: 4pt 4pt 4pt 4pt;">
0.91    
</td>
</tr>
<tr>
<td style="vertical-align: top; text-align: left; white-space: nowrap; padding: 4pt 4pt 4pt 4pt;">
logLik
</td>
<td style="vertical-align: top; text-align: right; white-space: nowrap; padding: 4pt 4pt 4pt 4pt;">
-2348.26    
</td>
<td style="vertical-align: top; text-align: right; white-space: nowrap; padding: 4pt 4pt 4pt 4pt;">
-1646.56    
</td>
<td style="vertical-align: top; text-align: right; white-space: nowrap; padding: 4pt 4pt 4pt 4pt;">
-2034.44    
</td>
<td style="vertical-align: top; text-align: right; white-space: nowrap; padding: 4pt 4pt 4pt 4pt;">
-1471.16    
</td>
</tr>
<tr>
<td style="vertical-align: top; text-align: left; white-space: nowrap; border-style: solid solid solid solid; border-width: 0pt 0pt 0.8pt 0pt; padding: 4pt 4pt 4pt 4pt;">
AIC
</td>
<td style="vertical-align: top; text-align: right; white-space: nowrap; border-style: solid solid solid solid; border-width: 0pt 0pt 0.8pt 0pt; padding: 4pt 4pt 4pt 4pt;">
4702.52    
</td>
<td style="vertical-align: top; text-align: right; white-space: nowrap; border-style: solid solid solid solid; border-width: 0pt 0pt 0.8pt 0pt; padding: 4pt 4pt 4pt 4pt;">
3301.12    
</td>
<td style="vertical-align: top; text-align: right; white-space: nowrap; border-style: solid solid solid solid; border-width: 0pt 0pt 0.8pt 0pt; padding: 4pt 4pt 4pt 4pt;">
4078.87    
</td>
<td style="vertical-align: top; text-align: right; white-space: nowrap; border-style: solid solid solid solid; border-width: 0pt 0pt 0.8pt 0pt; padding: 4pt 4pt 4pt 4pt;">
2958.32    
</td>
</tr>
<tr>
<td colspan="5" style="vertical-align: top; text-align: left; white-space: normal; padding: 4pt 4pt 4pt 4pt;">
*** p &lt; 0.001; ** p &lt; 0.01; * p &lt; 0.05.
</td>
</tr>
</table>
<p>Phew. All done!</p>
<h2 id="clearest-and-muddiest-things">Clearest and muddiest things</h2>
<p>Go to <a href="https://goo.gl/forms/PlPwZGhMOdU9mKfC3">this form</a> and answer these three questions:</p>
<ol style="list-style-type: decimal">
<li>What was the muddiest thing from class today? What are you still wondering about?</li>
<li>What was the clearest thing from class today?</li>
<li>What was the most exciting thing you learned?</li>
</ol>
<p>I’ll compile the questions and send out answers after class.</p>
